//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreamEnergy.StreamCommons.Account {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:webservice", ConfigurationName="StreamCommons.Account.CisAccountServicesPortType")]
    public interface CisAccountServicesPortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:xmethods) of message helloWorldRequest does not match the default value (urn:webservice)
        [System.ServiceModel.OperationContractAttribute(Action="urn:helloWorldAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StreamEnergy.StreamCommons.Account.helloWorldResponse1 helloWorld(StreamEnergy.StreamCommons.Account.helloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:helloWorldAction", ReplyAction="*")]
        System.Threading.Tasks.Task<StreamEnergy.StreamCommons.Account.helloWorldResponse1> helloWorldAsync(StreamEnergy.StreamCommons.Account.helloWorldRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:xmethods) of message echoTextRequest does not match the default value (urn:webservice)
        [System.ServiceModel.OperationContractAttribute(Action="urn:echoTextAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StreamEnergy.StreamCommons.Account.echoTextResponse1 echoText(StreamEnergy.StreamCommons.Account.echoTextRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:echoTextAction", ReplyAction="*")]
        System.Threading.Tasks.Task<StreamEnergy.StreamCommons.Account.echoTextResponse1> echoTextAsync(StreamEnergy.StreamCommons.Account.echoTextRequest1 request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:xmethods) of message getCisAccountsByUtilityAccountNumberRequest does not match the default value (urn:webservice)
        [System.ServiceModel.OperationContractAttribute(Action="urn:getCisAccountsByUtilityAccountNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StreamEnergy.StreamCommons.Account.getCisAccountsByUtilityAccountNumberResponse getCisAccountsByUtilityAccountNumber(StreamEnergy.StreamCommons.Account.getCisAccountsByUtilityAccountNumberRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getCisAccountsByUtilityAccountNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<StreamEnergy.StreamCommons.Account.getCisAccountsByUtilityAccountNumberResponse> getCisAccountsByUtilityAccountNumberAsync(StreamEnergy.StreamCommons.Account.getCisAccountsByUtilityAccountNumberRequest1 request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:xmethods) of message getCisAccountsByCisAccountNumberRequest does not match the default value (urn:webservice)
        [System.ServiceModel.OperationContractAttribute(Action="urn:getCisAccountsByCisAccountNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StreamEnergy.StreamCommons.Account.getCisAccountsByCisAccountNumberResponse getCisAccountsByCisAccountNumber(StreamEnergy.StreamCommons.Account.getCisAccountsByCisAccountNumberRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getCisAccountsByCisAccountNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<StreamEnergy.StreamCommons.Account.getCisAccountsByCisAccountNumberResponse> getCisAccountsByCisAccountNumberAsync(StreamEnergy.StreamCommons.Account.getCisAccountsByCisAccountNumberRequest1 request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:xmethods) of message linkCisAccountToCamelotAccountRequest does not match the default value (urn:webservice)
        [System.ServiceModel.OperationContractAttribute(Action="urn:linkCisAccountToCamelotAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StreamEnergy.StreamCommons.Account.linkCisAccountToCamelotAccountResponse1 linkCisAccountToCamelotAccount(StreamEnergy.StreamCommons.Account.linkCisAccountToCamelotAccountRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:linkCisAccountToCamelotAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<StreamEnergy.StreamCommons.Account.linkCisAccountToCamelotAccountResponse1> linkCisAccountToCamelotAccountAsync(StreamEnergy.StreamCommons.Account.linkCisAccountToCamelotAccountRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.streamenergy.net/Schema")]
    public partial class HelloWorldResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.streamenergy.net/Schema")]
    public partial class LinkCisAccountToCamelotAccountResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CustomerAccount customerAccountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public CustomerAccount customerAccount {
            get {
                return this.customerAccountField;
            }
            set {
                this.customerAccountField = value;
                this.RaisePropertyChanged("customerAccount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.streamenergy.net/Schema")]
    public partial class CustomerAccount : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cisAccountNumberField;
        
        private cisDesignationsType cisOfRecordField;
        
        private string camelotAccountNumberField;
        
        private string commodityField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string primaryPhoneField;
        
        private string emailAddressField;
        
        private Address billingAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cisAccountNumber {
            get {
                return this.cisAccountNumberField;
            }
            set {
                this.cisAccountNumberField = value;
                this.RaisePropertyChanged("cisAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public cisDesignationsType cisOfRecord {
            get {
                return this.cisOfRecordField;
            }
            set {
                this.cisOfRecordField = value;
                this.RaisePropertyChanged("cisOfRecord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string camelotAccountNumber {
            get {
                return this.camelotAccountNumberField;
            }
            set {
                this.camelotAccountNumberField = value;
                this.RaisePropertyChanged("camelotAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string commodity {
            get {
                return this.commodityField;
            }
            set {
                this.commodityField = value;
                this.RaisePropertyChanged("commodity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("lastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string primaryPhone {
            get {
                return this.primaryPhoneField;
            }
            set {
                this.primaryPhoneField = value;
                this.RaisePropertyChanged("primaryPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string emailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
                this.RaisePropertyChanged("emailAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public Address billingAddress {
            get {
                return this.billingAddressField;
            }
            set {
                this.billingAddressField = value;
                this.RaisePropertyChanged("billingAddress");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.streamenergy.net/Schema")]
    public enum cisDesignationsType {
        
        /// <remarks/>
        ARSENAL_TX,
        
        /// <remarks/>
        PEACEKEEPER_GA,
        
        /// <remarks/>
        ISTANET_NE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.streamenergy.net/Schema")]
    public partial class Address : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string streetField;
        
        private string street2Field;
        
        private string cityField;
        
        private string stateField;
        
        private string zipcodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string street2 {
            get {
                return this.street2Field;
            }
            set {
                this.street2Field = value;
                this.RaisePropertyChanged("street2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string zipcode {
            get {
                return this.zipcodeField;
            }
            set {
                this.zipcodeField = value;
                this.RaisePropertyChanged("zipcode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.streamenergy.net/Schema")]
    public partial class LinkCisAccountToCamelotAccountRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cisAccountNumberField;
        
        private string cisOfRecordField;
        
        private string camelotAccountNumberField;
        
        private string igniteAssociateNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cisAccountNumber {
            get {
                return this.cisAccountNumberField;
            }
            set {
                this.cisAccountNumberField = value;
                this.RaisePropertyChanged("cisAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cisOfRecord {
            get {
                return this.cisOfRecordField;
            }
            set {
                this.cisOfRecordField = value;
                this.RaisePropertyChanged("cisOfRecord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string camelotAccountNumber {
            get {
                return this.camelotAccountNumberField;
            }
            set {
                this.camelotAccountNumberField = value;
                this.RaisePropertyChanged("camelotAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string igniteAssociateNumber {
            get {
                return this.igniteAssociateNumberField;
            }
            set {
                this.igniteAssociateNumberField = value;
                this.RaisePropertyChanged("igniteAssociateNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.streamenergy.net/Schema")]
    public partial class GetCisAccountsByCisAccountNumberRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cisAccountNumberField;
        
        private string customerPinField;
        
        private string cisOfRecordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cisAccountNumber {
            get {
                return this.cisAccountNumberField;
            }
            set {
                this.cisAccountNumberField = value;
                this.RaisePropertyChanged("cisAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string customerPin {
            get {
                return this.customerPinField;
            }
            set {
                this.customerPinField = value;
                this.RaisePropertyChanged("customerPin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cisOfRecord {
            get {
                return this.cisOfRecordField;
            }
            set {
                this.cisOfRecordField = value;
                this.RaisePropertyChanged("cisOfRecord");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.streamenergy.net/Schema")]
    public partial class GetCisAccountsByUtilityAccountNumberRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string utilityAccountNumberField;
        
        private string customerPinField;
        
        private string cisOfRecordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string utilityAccountNumber {
            get {
                return this.utilityAccountNumberField;
            }
            set {
                this.utilityAccountNumberField = value;
                this.RaisePropertyChanged("utilityAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string customerPin {
            get {
                return this.customerPinField;
            }
            set {
                this.customerPinField = value;
                this.RaisePropertyChanged("customerPin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cisOfRecord {
            get {
                return this.cisOfRecordField;
            }
            set {
                this.cisOfRecordField = value;
                this.RaisePropertyChanged("cisOfRecord");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.streamenergy.net/Schema")]
    public partial class EchoTextResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.streamenergy.net/Schema")]
    public partial class EchoTextRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloWorld", WrapperNamespace="urn:xmethods", IsWrapped=true)]
    public partial class helloWorldRequest {
        
        public helloWorldRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloWorldResponse", WrapperNamespace="urn:xmethods", IsWrapped=true)]
    public partial class helloWorldResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public StreamEnergy.StreamCommons.Account.HelloWorldResponse HelloWorldResponse;
        
        public helloWorldResponse1() {
        }
        
        public helloWorldResponse1(StreamEnergy.StreamCommons.Account.HelloWorldResponse HelloWorldResponse) {
            this.HelloWorldResponse = HelloWorldResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoText", WrapperNamespace="urn:xmethods", IsWrapped=true)]
    public partial class echoTextRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public StreamEnergy.StreamCommons.Account.EchoTextRequest EchoTextRequest;
        
        public echoTextRequest1() {
        }
        
        public echoTextRequest1(StreamEnergy.StreamCommons.Account.EchoTextRequest EchoTextRequest) {
            this.EchoTextRequest = EchoTextRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoTextResponse", WrapperNamespace="urn:xmethods", IsWrapped=true)]
    public partial class echoTextResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public StreamEnergy.StreamCommons.Account.EchoTextResponse EchoTextResponse;
        
        public echoTextResponse1() {
        }
        
        public echoTextResponse1(StreamEnergy.StreamCommons.Account.EchoTextResponse EchoTextResponse) {
            this.EchoTextResponse = EchoTextResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCisAccountsByUtilityAccountNumber", WrapperNamespace="urn:xmethods", IsWrapped=true)]
    public partial class getCisAccountsByUtilityAccountNumberRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public StreamEnergy.StreamCommons.Account.GetCisAccountsByUtilityAccountNumberRequest GetCisAccountsByUtilityAccountNumberRequest;
        
        public getCisAccountsByUtilityAccountNumberRequest1() {
        }
        
        public getCisAccountsByUtilityAccountNumberRequest1(StreamEnergy.StreamCommons.Account.GetCisAccountsByUtilityAccountNumberRequest GetCisAccountsByUtilityAccountNumberRequest) {
            this.GetCisAccountsByUtilityAccountNumberRequest = GetCisAccountsByUtilityAccountNumberRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCisAccountsByUtilityAccountNumberResponse", WrapperNamespace="urn:xmethods", IsWrapped=true)]
    public partial class getCisAccountsByUtilityAccountNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCisAccountsByUtilityAccountNumberResponse", Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("customerAccount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public StreamEnergy.StreamCommons.Account.CustomerAccount[] GetCisAccountsByUtilityAccountNumberResponse1;
        
        public getCisAccountsByUtilityAccountNumberResponse() {
        }
        
        public getCisAccountsByUtilityAccountNumberResponse(StreamEnergy.StreamCommons.Account.CustomerAccount[] GetCisAccountsByUtilityAccountNumberResponse1) {
            this.GetCisAccountsByUtilityAccountNumberResponse1 = GetCisAccountsByUtilityAccountNumberResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCisAccountsByCisAccountNumber", WrapperNamespace="urn:xmethods", IsWrapped=true)]
    public partial class getCisAccountsByCisAccountNumberRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public StreamEnergy.StreamCommons.Account.GetCisAccountsByCisAccountNumberRequest GetCisAccountsByCisAccountNumberRequest;
        
        public getCisAccountsByCisAccountNumberRequest1() {
        }
        
        public getCisAccountsByCisAccountNumberRequest1(StreamEnergy.StreamCommons.Account.GetCisAccountsByCisAccountNumberRequest GetCisAccountsByCisAccountNumberRequest) {
            this.GetCisAccountsByCisAccountNumberRequest = GetCisAccountsByCisAccountNumberRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCisAccountsByCisAccountNumberResponse", WrapperNamespace="urn:xmethods", IsWrapped=true)]
    public partial class getCisAccountsByCisAccountNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCisAccountsByCisAccountNumberResponse", Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("customerAccount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public StreamEnergy.StreamCommons.Account.CustomerAccount[] GetCisAccountsByCisAccountNumberResponse1;
        
        public getCisAccountsByCisAccountNumberResponse() {
        }
        
        public getCisAccountsByCisAccountNumberResponse(StreamEnergy.StreamCommons.Account.CustomerAccount[] GetCisAccountsByCisAccountNumberResponse1) {
            this.GetCisAccountsByCisAccountNumberResponse1 = GetCisAccountsByCisAccountNumberResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="linkCisAccountToCamelotAccount", WrapperNamespace="urn:xmethods", IsWrapped=true)]
    public partial class linkCisAccountToCamelotAccountRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public StreamEnergy.StreamCommons.Account.LinkCisAccountToCamelotAccountRequest LinkCisAccountToCamelotAccountRequest;
        
        public linkCisAccountToCamelotAccountRequest1() {
        }
        
        public linkCisAccountToCamelotAccountRequest1(StreamEnergy.StreamCommons.Account.LinkCisAccountToCamelotAccountRequest LinkCisAccountToCamelotAccountRequest) {
            this.LinkCisAccountToCamelotAccountRequest = LinkCisAccountToCamelotAccountRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="linkCisAccountToCamelotAccountResponse", WrapperNamespace="urn:xmethods", IsWrapped=true)]
    public partial class linkCisAccountToCamelotAccountResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public StreamEnergy.StreamCommons.Account.LinkCisAccountToCamelotAccountResponse LinkCisAccountToCamelotAccountResponse;
        
        public linkCisAccountToCamelotAccountResponse1() {
        }
        
        public linkCisAccountToCamelotAccountResponse1(StreamEnergy.StreamCommons.Account.LinkCisAccountToCamelotAccountResponse LinkCisAccountToCamelotAccountResponse) {
            this.LinkCisAccountToCamelotAccountResponse = LinkCisAccountToCamelotAccountResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CisAccountServicesPortTypeChannel : StreamEnergy.StreamCommons.Account.CisAccountServicesPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CisAccountServicesPortTypeClient : System.ServiceModel.ClientBase<StreamEnergy.StreamCommons.Account.CisAccountServicesPortType>, StreamEnergy.StreamCommons.Account.CisAccountServicesPortType {
        
        public CisAccountServicesPortTypeClient() {
        }
        
        public CisAccountServicesPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CisAccountServicesPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CisAccountServicesPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CisAccountServicesPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StreamEnergy.StreamCommons.Account.helloWorldResponse1 StreamEnergy.StreamCommons.Account.CisAccountServicesPortType.helloWorld(StreamEnergy.StreamCommons.Account.helloWorldRequest request) {
            return base.Channel.helloWorld(request);
        }
        
        public StreamEnergy.StreamCommons.Account.HelloWorldResponse helloWorld() {
            StreamEnergy.StreamCommons.Account.helloWorldRequest inValue = new StreamEnergy.StreamCommons.Account.helloWorldRequest();
            StreamEnergy.StreamCommons.Account.helloWorldResponse1 retVal = ((StreamEnergy.StreamCommons.Account.CisAccountServicesPortType)(this)).helloWorld(inValue);
            return retVal.HelloWorldResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StreamEnergy.StreamCommons.Account.helloWorldResponse1> StreamEnergy.StreamCommons.Account.CisAccountServicesPortType.helloWorldAsync(StreamEnergy.StreamCommons.Account.helloWorldRequest request) {
            return base.Channel.helloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<StreamEnergy.StreamCommons.Account.helloWorldResponse1> helloWorldAsync() {
            StreamEnergy.StreamCommons.Account.helloWorldRequest inValue = new StreamEnergy.StreamCommons.Account.helloWorldRequest();
            return ((StreamEnergy.StreamCommons.Account.CisAccountServicesPortType)(this)).helloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StreamEnergy.StreamCommons.Account.echoTextResponse1 StreamEnergy.StreamCommons.Account.CisAccountServicesPortType.echoText(StreamEnergy.StreamCommons.Account.echoTextRequest1 request) {
            return base.Channel.echoText(request);
        }
        
        public StreamEnergy.StreamCommons.Account.EchoTextResponse echoText(StreamEnergy.StreamCommons.Account.EchoTextRequest EchoTextRequest) {
            StreamEnergy.StreamCommons.Account.echoTextRequest1 inValue = new StreamEnergy.StreamCommons.Account.echoTextRequest1();
            inValue.EchoTextRequest = EchoTextRequest;
            StreamEnergy.StreamCommons.Account.echoTextResponse1 retVal = ((StreamEnergy.StreamCommons.Account.CisAccountServicesPortType)(this)).echoText(inValue);
            return retVal.EchoTextResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StreamEnergy.StreamCommons.Account.echoTextResponse1> StreamEnergy.StreamCommons.Account.CisAccountServicesPortType.echoTextAsync(StreamEnergy.StreamCommons.Account.echoTextRequest1 request) {
            return base.Channel.echoTextAsync(request);
        }
        
        public System.Threading.Tasks.Task<StreamEnergy.StreamCommons.Account.echoTextResponse1> echoTextAsync(StreamEnergy.StreamCommons.Account.EchoTextRequest EchoTextRequest) {
            StreamEnergy.StreamCommons.Account.echoTextRequest1 inValue = new StreamEnergy.StreamCommons.Account.echoTextRequest1();
            inValue.EchoTextRequest = EchoTextRequest;
            return ((StreamEnergy.StreamCommons.Account.CisAccountServicesPortType)(this)).echoTextAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StreamEnergy.StreamCommons.Account.getCisAccountsByUtilityAccountNumberResponse StreamEnergy.StreamCommons.Account.CisAccountServicesPortType.getCisAccountsByUtilityAccountNumber(StreamEnergy.StreamCommons.Account.getCisAccountsByUtilityAccountNumberRequest1 request) {
            return base.Channel.getCisAccountsByUtilityAccountNumber(request);
        }
        
        public StreamEnergy.StreamCommons.Account.CustomerAccount[] getCisAccountsByUtilityAccountNumber(StreamEnergy.StreamCommons.Account.GetCisAccountsByUtilityAccountNumberRequest GetCisAccountsByUtilityAccountNumberRequest) {
            StreamEnergy.StreamCommons.Account.getCisAccountsByUtilityAccountNumberRequest1 inValue = new StreamEnergy.StreamCommons.Account.getCisAccountsByUtilityAccountNumberRequest1();
            inValue.GetCisAccountsByUtilityAccountNumberRequest = GetCisAccountsByUtilityAccountNumberRequest;
            StreamEnergy.StreamCommons.Account.getCisAccountsByUtilityAccountNumberResponse retVal = ((StreamEnergy.StreamCommons.Account.CisAccountServicesPortType)(this)).getCisAccountsByUtilityAccountNumber(inValue);
            return retVal.GetCisAccountsByUtilityAccountNumberResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StreamEnergy.StreamCommons.Account.getCisAccountsByUtilityAccountNumberResponse> StreamEnergy.StreamCommons.Account.CisAccountServicesPortType.getCisAccountsByUtilityAccountNumberAsync(StreamEnergy.StreamCommons.Account.getCisAccountsByUtilityAccountNumberRequest1 request) {
            return base.Channel.getCisAccountsByUtilityAccountNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<StreamEnergy.StreamCommons.Account.getCisAccountsByUtilityAccountNumberResponse> getCisAccountsByUtilityAccountNumberAsync(StreamEnergy.StreamCommons.Account.GetCisAccountsByUtilityAccountNumberRequest GetCisAccountsByUtilityAccountNumberRequest) {
            StreamEnergy.StreamCommons.Account.getCisAccountsByUtilityAccountNumberRequest1 inValue = new StreamEnergy.StreamCommons.Account.getCisAccountsByUtilityAccountNumberRequest1();
            inValue.GetCisAccountsByUtilityAccountNumberRequest = GetCisAccountsByUtilityAccountNumberRequest;
            return ((StreamEnergy.StreamCommons.Account.CisAccountServicesPortType)(this)).getCisAccountsByUtilityAccountNumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StreamEnergy.StreamCommons.Account.getCisAccountsByCisAccountNumberResponse StreamEnergy.StreamCommons.Account.CisAccountServicesPortType.getCisAccountsByCisAccountNumber(StreamEnergy.StreamCommons.Account.getCisAccountsByCisAccountNumberRequest1 request) {
            return base.Channel.getCisAccountsByCisAccountNumber(request);
        }
        
        public StreamEnergy.StreamCommons.Account.CustomerAccount[] getCisAccountsByCisAccountNumber(StreamEnergy.StreamCommons.Account.GetCisAccountsByCisAccountNumberRequest GetCisAccountsByCisAccountNumberRequest) {
            StreamEnergy.StreamCommons.Account.getCisAccountsByCisAccountNumberRequest1 inValue = new StreamEnergy.StreamCommons.Account.getCisAccountsByCisAccountNumberRequest1();
            inValue.GetCisAccountsByCisAccountNumberRequest = GetCisAccountsByCisAccountNumberRequest;
            StreamEnergy.StreamCommons.Account.getCisAccountsByCisAccountNumberResponse retVal = ((StreamEnergy.StreamCommons.Account.CisAccountServicesPortType)(this)).getCisAccountsByCisAccountNumber(inValue);
            return retVal.GetCisAccountsByCisAccountNumberResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StreamEnergy.StreamCommons.Account.getCisAccountsByCisAccountNumberResponse> StreamEnergy.StreamCommons.Account.CisAccountServicesPortType.getCisAccountsByCisAccountNumberAsync(StreamEnergy.StreamCommons.Account.getCisAccountsByCisAccountNumberRequest1 request) {
            return base.Channel.getCisAccountsByCisAccountNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<StreamEnergy.StreamCommons.Account.getCisAccountsByCisAccountNumberResponse> getCisAccountsByCisAccountNumberAsync(StreamEnergy.StreamCommons.Account.GetCisAccountsByCisAccountNumberRequest GetCisAccountsByCisAccountNumberRequest) {
            StreamEnergy.StreamCommons.Account.getCisAccountsByCisAccountNumberRequest1 inValue = new StreamEnergy.StreamCommons.Account.getCisAccountsByCisAccountNumberRequest1();
            inValue.GetCisAccountsByCisAccountNumberRequest = GetCisAccountsByCisAccountNumberRequest;
            return ((StreamEnergy.StreamCommons.Account.CisAccountServicesPortType)(this)).getCisAccountsByCisAccountNumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StreamEnergy.StreamCommons.Account.linkCisAccountToCamelotAccountResponse1 StreamEnergy.StreamCommons.Account.CisAccountServicesPortType.linkCisAccountToCamelotAccount(StreamEnergy.StreamCommons.Account.linkCisAccountToCamelotAccountRequest1 request) {
            return base.Channel.linkCisAccountToCamelotAccount(request);
        }
        
        public StreamEnergy.StreamCommons.Account.LinkCisAccountToCamelotAccountResponse linkCisAccountToCamelotAccount(StreamEnergy.StreamCommons.Account.LinkCisAccountToCamelotAccountRequest LinkCisAccountToCamelotAccountRequest) {
            StreamEnergy.StreamCommons.Account.linkCisAccountToCamelotAccountRequest1 inValue = new StreamEnergy.StreamCommons.Account.linkCisAccountToCamelotAccountRequest1();
            inValue.LinkCisAccountToCamelotAccountRequest = LinkCisAccountToCamelotAccountRequest;
            StreamEnergy.StreamCommons.Account.linkCisAccountToCamelotAccountResponse1 retVal = ((StreamEnergy.StreamCommons.Account.CisAccountServicesPortType)(this)).linkCisAccountToCamelotAccount(inValue);
            return retVal.LinkCisAccountToCamelotAccountResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StreamEnergy.StreamCommons.Account.linkCisAccountToCamelotAccountResponse1> StreamEnergy.StreamCommons.Account.CisAccountServicesPortType.linkCisAccountToCamelotAccountAsync(StreamEnergy.StreamCommons.Account.linkCisAccountToCamelotAccountRequest1 request) {
            return base.Channel.linkCisAccountToCamelotAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<StreamEnergy.StreamCommons.Account.linkCisAccountToCamelotAccountResponse1> linkCisAccountToCamelotAccountAsync(StreamEnergy.StreamCommons.Account.LinkCisAccountToCamelotAccountRequest LinkCisAccountToCamelotAccountRequest) {
            StreamEnergy.StreamCommons.Account.linkCisAccountToCamelotAccountRequest1 inValue = new StreamEnergy.StreamCommons.Account.linkCisAccountToCamelotAccountRequest1();
            inValue.LinkCisAccountToCamelotAccountRequest = LinkCisAccountToCamelotAccountRequest;
            return ((StreamEnergy.StreamCommons.Account.CisAccountServicesPortType)(this)).linkCisAccountToCamelotAccountAsync(inValue);
        }
    }
}
