//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.layouts.Pages.Marketing.Leaders {
    
    
    public partial class View_All_Directors {
        
        /// <summary>
        /// cusDirectors control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Website.layouts.Pages.Marketing.Leaders.Leader_Listing cusDirectors;
    }
}
