//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.layouts.Pages.Marketing.Historical_Rates {
    
    
    public partial class historical_rates_texas {
        
        /// <summary>
        /// rptVariablePricePlan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptVariablePricePlan;
        
        /// <summary>
        /// rptGreenAndCleanVariablePricePlan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptGreenAndCleanVariablePricePlan;
        
        /// <summary>
        /// rptFlexChoicePlan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptFlexChoicePlan;
        
        /// <summary>
        /// rptFlexChoicePlanGreenAndCleanPlan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptFlexChoicePlanGreenAndCleanPlan;
    }
}
