var $$FSR = {
   'timestamp': 'May 8, 2014 @ 4:25 PM',
   'version': '16.1.2.4',
   'build': '7',
   'enabled': true,
   'frames' : false,
   'sessionreplay': true,
   'auto' : true,
   'encode' : true,
   'files': '/foresee/',
   // needs to be set when foresee-transport.swf is not located at 'files'
   //'swf_files': '__swf_files_'
   'id': 'kzbIv02ODGyOI0exo0z+uQ==',
   'definition': 'foresee-surveydef.js',
   'swf' : 'foresee-transport.swf',
   'worker' : 'foresee-worker.js',
   'embedded': false,
   'replay_id': 'mystream.com',
   'attach': false,
   'renderer':'W3C',	// or "ASRECORDED"
   'layout':'CENTERFIXED',	// or "LEFTFIXED" or "LEFTSTRETCH" or "CENTERSTRETCH"
   'triggerDelay': undefined,
   'heartbeat' : true,
   'pools' : [
      {
         path: '.',
         sp: 100  // CHANGE ONLY WHEN INCLUDING SESSION REPLAY
      }
   ],
   'sites': [
      {
         path: /\w+-?\w+\.(com|org|edu|gov|net|co\.uk)/
      },
      {
         path: '.',
         domain: 'default'
      }
   ],
   storageOption: 'cookie',
   nameBackup:window.name
};

var FSRCONFIG = {};

// -------------------------------- DO NOT MODIFY ANYTHING BETWEEN THE DASHED LINES --------------------------------
if (typeof(FSR) == "undefined") {
(function(config){function A(){return function(){}}
(function(ba,Y){function x(a,b){return(b?a.get(b):a)||""}function L(a){return[a||g.g(),(a||g.g()).get("cp")||{}]}function T(a,b,c){var e=[];if(0<a.length){var f,k,h,l,s=a;a=/\.(?=([^"]*"[^"]*")*[^"]*$)|\[|#|:/g;var g=[];if(a.test(s)){a=s.match(a);for(var m=0;m<a.length;m++){var n=s.indexOf(a[m]);g.push({Ca:s.substr(0,n),oc:a[m]});s=s.substr(n)}}g.push({Ca:s});a=g[0].Ca.toUpperCase();for(s=g.length-1;1<=s;s--)m=g[s-1].oc,n=g[s].Ca,"["==m?(k=n.substr(1,n.length-2).split("="),1<k.length&&(k[1]=k[1].replace(/["']/g,
""))):"."==m?h=n.substr(1):"#"==m?f=n.substr(1):":"==m&&(l=parseInt(n.replace(":nth-child(","").replace(")","")));0==a.length&&(a="*");if(c)for(s=b.childNodes.length-1;0<=s;s--)c=b.childNodes[s],1!=c.nodeType||"*"!=a&&c.tagName!=a||e.push(c);else e=U(b.getElementsByTagName(a));if(f||k||h||l)for(s=e.length-1;0<=s;s--)l&&d.Qb(e[s])!=l-1||h&&-1==e[s].className.indexOf(h)||f&&e[s].id!=f?e.splice(s,1):k&&""!=k[0]&&(b=k[0],c=k[1]||"",g=e[s].getAttribute(b)||"","id"==b?c!=g&&e.splice(s,1):0>g.indexOf(c)&&
e.splice(s,1))}return e}function U(a){var b=[],c,d=0;for(c=b.length=a.length;d<c;d++)b[d]=a[d];return b}function M(a,b){var c,d,f,k,h=w,l,g=b[a];g&&("object"===typeof g&&"function"===typeof g.toJSON)&&(g=g.toJSON(a));"function"===typeof z&&(g=z.call(b,a,g));switch(typeof g){case "string":return O(g);case "number":return isFinite(g)?String(g):"null";case "boolean":case "null":return String(g);case "object":if(!g)return"null";w+=F;l=[];if("[object Array]"===Object.prototype.toString.apply(g)){k=g.length;
for(c=0;c<k;c+=1)l[c]=M(c,g)||"null";f=0===l.length?"[]":w?"[\n"+w+l.join(",\n"+w)+"\n"+h+"]":"["+l.join(",")+"]";w=h;return f}if(z&&"object"===typeof z)for(k=z.length,c=0;c<k;c+=1)"string"===typeof z[c]&&(d=z[c],(f=M(d,g))&&l.push(O(d)+(w?": ":":")+f));else for(d in g)Object.prototype.hasOwnProperty.call(g,d)&&(f=M(d,g))&&l.push(O(d)+(w?": ":":")+f);f=0===l.length?"{}":w?"{\n"+w+l.join(",\n"+w)+"\n"+h+"}":"{"+l.join(",")+"}";w=h;return f}}function O(a){P.lastIndex=0;return P.test(a)?'"'+a.replace(P,
function(a){var c=Z[a];return"string"===typeof c?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function $(a,b){var c=[],d;for(d in a)a.hasOwnProperty(d)&&(c[d]=b(a[d]));return c}var d={},l=l=window,t=l.document;d.Ma=864E5;d.F=!!t.attachEvent;var G=Object.prototype.hasOwnProperty,B=[],H=!1,D,B=[],H=!1;d.l=function(a){return null!==a&&void 0!==a};d.Ob=function(a){for(var b=a.length-1;0<=b;b--)for(var c=b-1;0<=c;c--)a[c]==a[b]&&a.splice(b,1);return a};d.Qb=function(a){for(var b=
a.parentNode.childNodes,c,d=count=0;(c=b.item(d++))&&c!=a;)1==c.nodeType&&count++;return count};d.ia=function(a){return"[object Array]"==Object.prototype.toString.call(a)};d.Fa=function(a){if(a){if(a.length)for(var b=a.length-1;0<=b;b--)a[b]=null;for(var c in a)if(b=typeof a[c],"function"==b||"object"==b)a[c]=null}};d.D=function(a){return"function"==typeof a};d.cc=function(a){return"object"==typeof a};d.trim=function(a){return a.toString().replace(/\s+/g," ").replace(/^\s+|\s+$/g,"")};d.Mc=function(a){var b=
a.getAttribute?a.getAttribute("id"):a.id;b&&!d.Qc(b)&&(b=a.attributes.id.value);return b};d.Rb=function(a){return a.toString().replace(/([-.*+?^${}()|[\]\/\\])/g,"\\$1")};d.n=function(){var a=arguments,b=a[0]||{},c=1,e=a.length,f,k,h;"object"===typeof b||d.D(b)||(b={});e===c&&(b=this,--c);for(;c<e;c++)if(null!=(f=a[c]))for(k in f)h=f[k],b!==h&&void 0!==h&&(b[k]=h);return b};d.H=A();d.now=function(){return+new Date};d.shift=function(a){return a.splice(0,1)[0]};d.Ta=function(a,b){for(var c in b)if(b[c]===
a)return c;return-1};d.R=function(){return t.location.protocol};d.Oc=function(a,b){return-1!=d.Ta(a,b)};d.Fc=function(a){return t.getElementById(a)};d.Hc=function(a,b,c){var e=a.split(".");b=b[d.shift(e)];for(var f=c,k;null!=b&&0<e.length;)b=b[d.shift(e)];if(b){for(e=a.split(".");e.length&&(k=d.shift(e));)f=f[k]?f[k]:f[k]={};e=a.split(".");for(f=c;e.length&&(k=d.shift(e));)0<e.length?f=f[k]:f[k]=b}};d.U=function(){return t.location.href};d.ga=function(a){return encodeURIComponent(a)};d.ta=function(a){return decodeURIComponent(a)};
d.Xa=function(){return t.referrer};d.Tc={};d.hc=function(a,b){a=a+"?build="+m.build;b=b||d.H;var c=t.createElement("script");c.type="text/javascript";d.F?c.onreadystatechange=function(){"loaded"!=this.readyState&&"complete"!=this.readyState||b("ok")}:c.onload=function(){b("ok")};c.onerror=function(){b("error")};c.src=0==d.Ta("//",a)?d.R()+a:a;(t.getElementsByTagName("head")[0]||t.documentElement).appendChild(c)};d.M=function(a,b,c){c||(c=l);c=c.document;c=c.readyState;b=b||1;if(d.D(a)&&(a=function(a,
b){return function(){setTimeout(function(a){return function(){a.call(d.ra);a=null}}(a),b);a=null}}(a,b),c&&("complete"==c||"loaded"==c))){H=!0;for(B.push(a);a=d.shift(B);)a&&a.call(d.ra);return}if(!H&&d.D(a))B.push(a);else if(H&&d.D(a))a.call(d.ra);else if(!d.D(a))for(H=!0;0<B.length;)(a=d.shift(B))&&a.call(d.ra);a=c=c=c=null};t.addEventListener?D=function(){-1<"complete,loaded".indexOf(t.readyState)&&(t.removeEventListener("readystatechange",D,!1),d.M(null))}:d.F&&(D=function(){-1<"complete,loaded".indexOf(t.readyState)&&
(t.detachEvent("onreadystatechange",D),d.M(null))});t.addEventListener?(t.addEventListener("readystatechange",D,!1),t.addEventListener("DOMContentLoaded",d.M,!1)):d.F&&t.attachEvent("onreadystatechange",D);d.match=function(a){for(var b=[["urls",d.U()],["local",d.U()],["referrers",d.Xa()],["referrer",d.Xa()],["userAgents",l.navigator.userAgent],["browsers",{name:u.f.name,version:u.f.L}]],c=0;c<b.length;c++)for(var e=b[c],f=a[e[0]]||[],k=0;k<f.length;k++){var h=f[k];if(!d.cc(e[1])){if(d.ta(e[1]).match(h))return!0}else if(d.ta(e[1].name.toLowerCase()).match(h.name.toLowerCase())&&
(!h.version||e[1].version==h.version))return!0}f=a.cookies||[];for(c=0;c<f.length;c++)if(e=f[c],b=g.h.Y(e.name))if(!e.operator||"eq"==e.operator){if(b.match(e.value||"."))return!0}else if((e.operator||"neq"==e.operator)&&null==b.match(e.value))return!0;c=g.Oa("fsr.ipo",g.cb("fsr.ipo"));if(a=a.variables)for(e=0,f=a.length;e<f;e++)if(b=a[e].name,k=a[e].value,b!=v.ipexclude||1!=c.get("value")){d.ia(b)||(b=[b],k=[k]);for(var m,h=!0,n=0,q=b.length,p=k.length;n<q&&n<p;n++){try{m=(new Function("return "+
b[n]))(),d.l(m)||(m="")}catch(r){m=""}var I;a:{I=m;var J=k[n];d.ia(J)||(J=[J]);for(var Q=0,t=J.length;Q<t;Q++)if((I+"").match(J[Q])){I=!0;break a}I=!1}if(!I){h=!1;break}}if(h)return!0}return!1};d.startTime=d.now();var v={},m=d.n({replay_id:"sitecom",site:{domain:"site.com"},renderer:"W3C",layout:"",swf_files:"/"},Y||{});d.V=function(){for(var a={},b=arguments,c=0,e=b.length;c<e;c++){var f=b[c];if(d.ja(f))for(var k in f){var h=f[k],g=a[k];a[k]=g&&d.ja(h)&&d.ja(g)?d.V(g,h):d.Ha(h)}}return a};d.Ha=function(a){var b;
if(d.ja(a)){b={};for(var c in a)b[c]=d.Ha(a[c])}else if(d.ia(a)){b=[];c=0;for(var e=a.length;c<e;c++)b[c]=d.Ha(a[c])}else b=a;return b};d.ja=function(a){if(!a||("[object Object]"!==Object.prototype.toString.call(a)||a.nodeType||a.setInterval)||a.constructor&&!G.call(a,"constructor")&&!G.call(a.constructor.prototype,"isPrototypeOf"))return!1;for(var b in a);return void 0===b||G.call(a,b)||!G.call(a,b)&&G.call(Object.prototype,b)};d.fa=function(){B=m=null;d=l=l.FSR=null};d.Nc=function(a){var b=d.now(),
c;do c=d.now();while(c-b<a)};if(d.l(l.FSRCONFIG)){var p=l.FSRCONFIG;p.surveydefs&&(d.surveydefs=p.surveydefs,p.surveydefs=null);p.properties&&(d.properties=p.properties,p.properties=null)}l.FSR=d;l.FSR.opts=m;l.FSR.prop=v;d.t={};d.t.yb={};var n=d.t.yb;n.Kc=function(){for(var a=u.pa.replace(/[\s\\\/\.\(\);:]/gim,""),b="",c=d.now()+"",e=0;e<a.length-1;e+=a.length/7)b+=Number(a.charCodeAt(Math.round(e))%16).toString(16);7<b.length&&(b=b.substr(b.length-7));return b+"-"+a.length+c.substr(c.length-6)+
"-xxxx-xxxx-xxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;return("x"==a?b:b&3|8).toString(16)})};n.Uc=function(a,b){return a+Math.random()*(b-a)};n.uc=function(a,b){var c=l.document.createElement("a");c.href=l.location.href;var d=c.hostname,f=c.protocol;c.href=a;var k=c.hostname||d,h=0==c.protocol.indexOf("http")?c.protocol:f;c.href=b;f=0==c.protocol.indexOf("http")?c.protocol:f;return k.toLowerCase()==(c.hostname||d).toLowerCase()&&h.toLowerCase()==f.toLowerCase()};n.s=function(a,b,
c){var e="";if(a)for(var f in a)e+=(0!=e.length?"&":"")+(b?b+"["+f+"]":f)+"="+(c?a[f]:d.ga(a[f]));return e};n.hash=function(a){a=a.split("_");return 3*a[0]+1357+""+(9*a[1]+58)};n.Yb=function(a){var b=0,c="";if(0==a.length)return b;for(y=0;y<a.length;y++)c=a.charCodeAt(y),b=(b<<5)-b+c,b&=b;return b};n.Aa=function(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");a=RegExp("[\\?&+]"+a+"=([^&#]*)").exec(d.U());return null==a?!1:a[1]};n.ua=function(a,b,c){return a[b]||a[c]};n.Sc=function(a){a=a.replace(/[^0-9]/g,
"");return 10==a.length||"1"==a[0]&&11==a.length};n.Rc=function(a){return null!=a.match(/^([a-zA-Z0-9_\.\-\+])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,6})+$/)};d.t.sb={};var r=d.t.sb;d.t.qb={};p=d.t.qb;p.Dc=function(a,b){var c,e,f;d.l(a.length)||(a=[a]);c=0;for(e=a.length;c<e;c++){f=a[c];var k=f.className||"";RegExp("\\b"+b+"\\b").test(k)||(f.className=(""==k?"":k+" ")+b)}};p.Vc=function(a,b){var c,e,f;d.l(a.length)||(a=[a]);c=0;for(e=a.length;c<e;c++)f=a[c],f.className&&(f.className=f.className.replace(RegExp("(\\s|^)"+
b+"(\\s|$)")," ").replace(/^\s+|\s+$/g,""))};p.Ic=function(a,b){if(a){d.l(a.length)||(a=[a]);for(var c=0;c<a.length;c++)for(var e in b)e&&(-1=="zIndex".indexOf(e)&&("number"==typeof b[e]&&"opacity"!=e)&&(b[e]+="px"),a[c].style[e]=b[e])}return a};p.Ec=function(a,b){if(a){d.l(a.length)||(a=[a]);for(var c=0;c<a.length;c++)for(var e in b)a[c].setAttribute(e,b[e])}return a};p.outerHTML=function(a){if(d.l(a.outerHTML))return a.outerHTML;var b={TEXTAREA:!0},c={HR:!0,BR:!0,IMG:!0,INPUT:!0},e=[],f="",k=a.nodeName;
switch(a.nodeType){case 1:f=f+"<"+k.toLowerCase();if(b[k])switch(k){case "TEXTAREA":for(b=0;b<a.attributes.length;b++)if("value"!=a.attributes[b].nodeName.toLowerCase())f+=" "+a.attributes[b].nodeName.toUpperCase()+'="'+a.attributes[b].nodeValue+'"';else var h=a.attributes[b].nodeValue;f+=">";f+=h;f+="</"+k+">"}else{for(b=a.attributes.length-1;0<=b;b--)h=a.attributes[b].nodeName.toLowerCase(),-1<"style,class,id".indexOf(h.toLowerCase())&&(f+=" "+h+'="'+a.attributes[b].nodeValue+'"');f+=">";c[k]||
(f+=a.innerHTML,f+="</"+k.toLowerCase()+">")}break;case 3:f+=a.nodeValue;break;case 8:f+="\x3c!--"+a.nodeValue+"--\x3e"}e.push(f);return e.join("")};d.stringify=function(a,b,c){var e;l.Prototype&&(e=Array.prototype.toJSON,delete Array.prototype.toJSON);if(l.JSON&&"function"===typeof l.JSON.stringify)a=l.JSON.stringify(a,b,c);else{var f;F=w="";if("number"===typeof c)for(f=0;f<c;f+=1)F+=" ";else"string"===typeof c&&(F=c);if((z=b)&&"function"!==typeof b&&("object"!==typeof b||"number"!==typeof b.length))throw Error("_4c.stringify");
a=M("",{"":a})}d.l(e)&&(Array.prototype.toJSON=e);return a};d.parse=function(a){if(l.JSON&&d.D(l.JSON.parse))return l.JSON.parse(a);a=String(a);R.lastIndex=0;R.test(a)&&(a=a.replace(R,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return(new Function("return "+a))();throw new SyntaxError("_4c.parse");
};for(var R=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,P=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,w,F,Z={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},z,S={},K=["onload","onerror","onabort"],y=0;y<K.length;y++)S[K[y]]=function(){this.kc(0==arguments.callee.Zb?1:0);this.v=!1},S[K[y]].Zb=y;r.K=function(a,b){this.options=d.n({},
a);this.v=!1;this.event=b;this.Ja=0;return this};r.K.prototype.kc=function(a){if(this.v)switch(this.v=!1,this.status=a,a){case 1:(this.options.onSuccess||d.H)(void 0);break;case 0:this.event?this.vc():(this.options.onFailure||d.H)(void 0);break;case -1:(this.options.onError||d.H)(void 0)}};r.K.prototype.vc=function(){if(3>this.Ja)this.Ra();else this.onFailure()};r.K.prototype.Lb=function(a){var b;this.v=!0;a=n.s(d.n(a,{uid:d.now()}));a=d.R()+"//"+this.options.host+this.options.path+this.options.url+
"?"+a;b=d.n({},S,b);for(var c=new Image,e=0;e<K.length;e++){var f=K[e];c[f]=function(){var a=arguments.callee;a.S.onload=a.S.onerror=a.S.onabort=null;a.Tb.call(a.self,a.S);a.S=null};c[f].Tb=b[f];c[f].S=c;c[f].self=this}c.src=a};r.K.prototype.send=function(a){this.xc=a;this.Ra()};r.K.prototype.Ra=function(){var a;this.Ja++;a=d.n({event:this.event,ver:this.Ja},this.xc,a);this.Lb(a)};n.k={};n.k.O={};n.k.ca=function(a,b,c,e){var f=n.k.O;if(a){f[b]||(f[b]=[]);f[b].push({Ya:a,ea:c});if("unload"==b){if(d.l(d.ba)){d.ba.push(c);
return}d.ba=[]}"propertychange"!=b&&a.addEventListener?a.addEventListener(b,c,!e):a.attachEvent&&a.attachEvent("on"+b,c)}};n.k.zc=function(a,b,c,d,f){var k=n.k;if(f){if(a.getAttribute("_fsr"+b))return!1;a.setAttribute("_fsr"+b,"true")}else if(f=k.O[b])for(k=f.length-1;0<=k;k--)if(f[k].Ya==a&&(d||f[k].ea==c))return!1;n.k.ca(a,b,c)};n.k.Ac=function(a,b,c){n.k.ca(a,b,c,!0)};n.k.xb=function(a,b,c){try{"propertychange"!=b&&a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+
b,c)}catch(d){}};var V=n.k.ca;n.k.rb=function(){for(var a=d.ba.length-1;0<=a;a--)try{d.ba[a].call()}catch(b){}d.Fa(d.ba);n.k.ub();d.fa()};V(l,"unload",n.k.rb);n.k.ub=function(){if(d){var a=n.k,b;for(b in a.O){for(var c=a.O[b],e={};e=c.pop();)a.xb(e.Ya,b,e.ea),d.Fa(e);delete a.O[b]}}};n.k.ma=function(){this.Z=[];this.Pb=!1};n.k.ma.prototype.sc=function(a){this.Z[this.Z.length]={lc:!1,ea:a}};n.k.ma.prototype.C=function(){this.Pb=!0;for(var a=0;a<this.Z.length;a++){var b=this.Z[a];b.ea.apply(this,arguments);
b.lc&&(this.Z.splice(a,1),a--)}};var E=n.k.ma;p.tb={Bc:{}};try{Array.prototype.slice.call(document.getElementsByTagName("html")),makeArray=function(a){return Array.prototype.slice.call(a)}}catch(ca){}var aa=p.tb.Wc=function(a,b,c){b=b||t;c=!d.l(d.na)||!d.na.da.Xc||c;if(b.querySelectorAll&&!(d.F&&8>=u.f.L&&-1<a.indexOf("nth")))return U(b.querySelectorAll(a));if(!c&&l.$&&!l.Prototype)return l.$(a,b);a=a.split(",");c=[];for(var e=a.length-1;0<=e;e--){var f=a[e].replace(/^\s\s*/,"").replace(/\s\s*$/,
"").replace(/\*=/g,"=").replace(/\>/g," > ").replace(/\s+/g," ");if(-1<f.indexOf(" ")){for(var f=f.split(" "),k=[b],h=!1,g=0;g<f.length;g++)if(">"==f[g])h=!0;else{for(var m=[],n=k.length-1;0<=n;n--)m=m.concat(T(f[g],k[n],h));k=m;h=!1}c=c.concat(d.Ob(k))}else c=c.concat(T(f,b))}return c};r.j=function(a,b){var c={method:"POST",url:d.U(),data:{},contentType:"application/x-www-form-urlencoded",I:d.H,B:d.H};this.ob=this.Ia=!1;var e=n.ua;if(l.Worker&&!b){var f=n.uc,k=e(m.site,"js_files","files");if(f(k,
l.location.href))this.Fb(k+(m.worker||"foresee-worker.js"));else{var e=e(m.site,"html_files","files"),h=document.createElement("a");h.href=e;(this.wa=h.protocol+"//"+h.hostname)&&f(e,k)&&(this.Eb(e+"iframe_proxier.html"),k!=e&&this.Gb(k+"foresee_worker.js"))}}this.options=d.n(c,a)};r.j.prototype.send=function(a,b){var c=d.n(this.options,a);!l.XDomainRequest||"IE"==u.f.name&&10<=u.f.L?this.ob&&!b?this.Sa(c):this.Ia&&!b?this.Ib(c):l.XMLHttpRequest&&this.Kb(c):this.Jb(c)};r.j.prototype.fa=function(){this.la&&
this.la.terminate();this.w&&(this.w.parentNode.removeChild(ifr),ifr=null);d.Fa(this.options)};r.j.isSupported=function(){return d.F&&10>u.f.L&&"https"!=d.U().substring(0,5)&&l==l.top?!1:!0};r.j.eb=function(a){a.call(r.j)};r.j.prototype.Eb=function(a){this.w=document.createElement("iframe");this.w.src=a;this.w.onload=r.j.Bb(this);this.w.style.display="none";document.body.appendChild(this.w);this.aa=0;this.X={};this.ob=!0;V(l,"message",function(a){return function(c){r.j.Pa(a,c)}}(this))};r.j.prototype.Fb=
function(a){try{this.la=new Worker(a),this.Ia=!0}catch(b){}this.Ia&&(this.aa=0,this.X={},this.la.onmessage=function(a){return function(b){r.j.Pa(a,b)}}(this))};r.j.Pa=function(a,b){var c=a.X[b.data.i];switch(b.data.status){case 200:c.I&&c.I.call(c,b.data.rt);break;case -1:d.Na.Va();break;default:c.B&&c.B.call(c,b.data.rt)}delete a.X[b.data.i]};r.j.Bb=function(a){return function(){a.$b=!0;if(a.J)for(var b=0;b<a.J.length;b++)a.Sa(a.J[b]);a.J=null}};r.j.prototype.Kb=function(a){var b=new l.XMLHttpRequest,
c=d.l(a.Da)&&!0==a.Da?a.data:n.s(a.data,null,!1);try{b.open(a.method,a.url,!0)}catch(e){d.Na.Va();return}b.setRequestHeader("Accept","*/*");b.setRequestHeader("Content-Type",a.contentType);b.onreadystatechange=function(a,b){return function(){4==b.readyState&&200==b.status?a.I&&a.I.apply(a,[b.responseText]):4==b.readyState&&200!=b.status&&a.B&&a.B.apply(a,[b.responseText])}}(a,b);b.send(c)};r.j.prototype.Ib=function(a){a=d.n(this.options,a);this.X[++this.aa]=a;this.la.postMessage(r.j.Qa(a,this.aa))};
r.j.prototype.Sa=function(a){var b=d.n(this.options,a);this.$b?(this.X[++this.aa]=b,this.w.contentWindow.postMessage(r.j.Qa(b,this.aa),this.wa)):this.J?this.J[this.J.length]=a:this.J=[a]};r.j.prototype.Jb=function(a){var b=d.l(a.Da)&&!0==a.Da?a.data:n.s(a.data,null,!1),c=new l.XDomainRequest;c.onerror=a.B;c.ontimeout=a.B;c.onprogress=d.H;c.onload=function(a,b){return function(){b.I(a.responseText);b=a=null}}(c,a);c.timeout=3E4;try{c.open("post",a.url)}catch(e){d.Na.Va();return}c.send(b)};r.j.prototype.Gb=
function(a){var b={m:"worker_url"};b.u=a;this.w.contentWindow.postMessage(b,this.wa)};r.j.Qa=function(a,b){var c={i:b},d=["method","url","data","contentType"],f;for(f in d)c[d[f]]=a[d[f]];return{m:"CORS",d:c}};d.t.na={};var q=d.t.na;q.Vb=function(a,b){for(var c=a.name,d=[a.site,a.section,b,g.g("q"),g.g("l")],f=0;f<d.length;f++)c+=d[f]?"-"+d[f]:"";return c};q.ic=function(a,b){function c(b){"ok"===b&&d.surveydefs&&(d.n(v,d.properties),m.Ga=m.surveydefs=d.surveydefs,a())}var e=m.definition||"foresee-surveydef.js";
b?setTimeout(function(){c("ok")},100):d.hc(n.ua(m.site,"js_files","files")+e,c)};q.log=function(a,b){if(v.events.enabled){var c=g.g(),e=c.get("sd");d.l(e)||(e=c.get("cd"));d.l(e)||(e=0);var e=m.Ga[e],f=new Date;(new r.K((new q.P(v)).event(),"logit")).send({cid:m.id,rid:c.get("rid")||"",cat:e.name,sec:e.section||"",type:c.get("q")||"",site:m.site.name||"",lang:c.get("l")||(d.$S?d.$S.locale:""),msg:a,param:b,tms:f.getTime(),tmz:6E4*f.getTimezoneOffset()})}};d.t.vb={};var g=d.t.vb;g.bb=function(a){return a+
(m.site.cookie?"."+m.site.cookie:"")};g.g=function(a,b){var c=g.bb("fsr.s"),c=g.Oa(c,g.cb(c));return a?d.l(b)?c.set(a,b):c.get(a):c};g.cb=function(a){var b;b="window"==m.storageOption&&g.zb.isSupported()?function(){var a=arguments.callee;return new g.zb(a.hb,a.$a||{})}:function(){var a=arguments.callee;return new g.h(a.hb,d.n({path:"/",domain:a.za.site.domain,secure:a.za.site.secure,encode:a.za.encode},a.$a||{}))};b.hb=a;b.za=m;b.$a=void 0;return b};var W={};g.Oa=function(a,b){var c=W[a];return null!=
c?c:c=W[a]=new b};n.pb=function(){function a(){d.M(function(a,b,c){return function(){a.ya=b();a.dc=c();a.gb=!0;a.Ua.C()}}(h,e,b))}function b(){var a=!0;h.G&&(h.ya=e(),"Android"==h.p.name&&(2.2>h.p.version?a=!1:3>h.p.version&&h.ya&&(a=!1)));return a}function c(){h.f.name=m.name;h.f.version=m.version;h.f.L="IE"!=h.f.name?h.f.version:6<h.f.version&&10>h.f.version?k("Trident")||7!=h.f.version?k("Trident/5.0")&&9>=h.f.version?9:k("Trident/4.0")&&9>h.f.version?8:h.f.version:7:h.f.version;h.p.name=f(h.G);
var a=h.p,b;h.G?(b=g.match(/Android[\/\s](\d+\.?\d+)/)||g.match(/Windows Phone OS[\/\s](\d+\.?\d+)/)||g.match(/Windows Phone[\/\s](\d+\.?\d+)/),b=null==b?1:b[1]):b=1;a.version=b}function e(){if("Winphone"!=h.p.name){var a=aa("head meta[name=viewport],head meta[name=VIEWPORT],head meta[name=Viewport]")||[];d.ia(a)||(a=[a]);if(0<a.length)for(var b=0;b<a.length;b++){var c=function(a,b){return a.match(RegExp("[\\w\\W]*"+b+"[\\s]*=[\\s]*([^\\s,;]*)[\\w\\W]*","i"))},e=c(a[b].content,"user-scalable"),f=
c(a[b].content,"initial-scale"),c=c(a[b].content,"maximum-scale");if(e&&1<e.length&&(0<="iphone,ipad,ipod".indexOf(h.p.name.toLowerCase())&&"0"==e[1].toLowerCase()||0<="android".indexOf(h.p.name.toLowerCase())&&"no"==e[1].toLowerCase()))return!1;if(f&&c)return!("1.0"==f[1]&&"1.0"==c[1])}return!0}return!1}function f(a){if(a)return k("iPod")?"iPod":k("iPad")?"iPad":k("iPhone")?"iPhone":(k("blackberry")||k("playbook")||k("BB10"))&&k("applewebkit")?"Blackberry":k("Windows Phone")?"Winphone":k("Kindle")||
k("Silk")?"Kindle":k("BNTV")||k("Nook")?"Nook":k("Android")?"Android":void 0!=l.orientation?"Mobile":"Other";if(k("Windows"))return"Windows";if(k("OS X"))return"Mac";if(k("Linux"))return"Linux";if(k("Mac"))return"Mac"}function k(a){return-1<g.toLowerCase().indexOf(a.toLowerCase())}var h=this;h.p={name:"",version:0};h.f={name:"",version:0,L:0};h.pa="";h.G=!1;h.xa=!1;h.dc=!0;h.ya=!0;h.gb=!1;h.Ua=new E;h.fb=!1;h.kb=d.R()+"//device.4seeresults.com/detect?accessToken=";var g=h.pa=l.navigator.userAgent;
h.G=/iphone|ipad|ipod|android|kindle|silk|bntv|nook|blackberry|playbook|mini|windows\sce|windows\sphone|palm|bb10/i.test(g);h.ec=/Windows Phone/i.test(g);h.G&&(/iphone|ipad|ipod/i.test(g)&&(h.fb=!0),/ipad|silk|kindle|playbook|nook|bntv/i.test(g)&&(h.xa=!0));var m=function(a){var b="Unknown",c;null!=(c=a.match(/Opera[\/\s](\d+\.\d+)/))?b="Opera":null!=(c=a.match(/MSIE (\d+\.\d+)/))?b="IE":null!=(c=a.match(/Navigator[\/\s](\d+\.\d+)/))?b="Netscape":null!=(c=a.match(/Chrome[\/\s](\d+\.\d+)/))?b="Chrome":
null!=(c=a.match(/Safari[\/\s](\d+\.?\d+)/))?b="Safari":null!=(c=a.match(/Firefox[\/\s](\d+\.\d+)/))&&(b="Firefox");return{name:b,version:null!=c?parseFloat(c[1]):void 0}}(g);if(h.G)if(h.fb||""==h.kb||h.xa||h.ec)c(),a(),a();else{var q=function(b){b=d.parse(b);h.f.name=b.browser.name;h.f.version=h.f.L=b.browser.version;h.p.name=b.os.name;h.p.version=b.os.version;h.G=b.isMobile;h.xa=b.isTablet;a()},p;if(l.sessionStorage){var t=l.sessionStorage;p=t.getItem("FSR_BROWSER")}p?q(p):(p={method:"GET",url:h.kb+
n.Yb(function(){var a=new Date,b=(a.getMonth()+1).toString(),c=a.getDate().toString();return a.getFullYear().toString()+(b[1]?b:"0"+b[0])+(c[1]?c:"0"+c[0])}()+"ForeSee"+(l.location.origin||"null"))+"&ua="+g,type:"*/*",contentType:"application/x-www-form-urlencoded",I:function(a){t&&t.setItem("FSR_BROWSER",a);q(a)},B:function(){c();a();a()}},(new r.j(p,!0)).send())}else c(),h.gb=!0,h.Ua.C()};var u=new n.pb,p={width:"1",height:"1",id:"_"+(""+Math.random()).slice(9),allowfullscreen:!0,allowscriptaccess:"always",
quality:"high",version:[3,0],jc:null,Sb:null,Ka:!1,Mb:!1};l.attachEvent&&l.attachEvent("onunload",function(){__flash_unloadHandler=A();__flash_savedUnloadHandler=A()});var N=d.n(d.Jc,{Gc:p,Wb:function(){var a,b;try{b=navigator.plugins["Shockwave Flash"].description.slice(16)}catch(c){try{b=(a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"))&&a.GetVariable("$version")}catch(d){try{b=(a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"))&&a.GetVariable("$version")}catch(f){}}}return(b=/(\d+)[^\d]+(\d+)[^\d]*(\d*)/.exec(b))?
[b[1],b[3]]:[0,0]},qa:function(a){if(null===a||void 0===a)return null;var b=typeof a;"object"==b&&a.push&&(b="array");switch(b){case "string":return a=a.replace(RegExp('(["\\\\])',"g"),"\\$1"),a=a.replace(/^\s?(\d+\.?\d*)%/,"$1pct"),'"'+a+'"';case "array":return"["+$(a,function(a){return N.qa(a)}).join(",")+"]";case "function":return'"function()"';case "object":var b=[],c;for(c in a)a.hasOwnProperty(c)&&b.push('"'+c+'":'+N.qa(a[c]));return"{"+b.join(",")+"}"}return String(a).replace(/\s/g," ").replace(/\'/g,
'"')},Lc:function(a,b){a=d.n({},a);var c='<object width="'+a.width+'" height="'+a.height+'" id="'+a.id+'" name="'+a.id+'"';a.Mb&&(a.src+=(-1!=a.src.indexOf("?")?"&":"?")+Math.random());c=a.Ka||!d.F?c+(' data="'+a.src+'" type="application/x-shockwave-flash"'):c+' classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"';c+=">";if(a.Ka||d.F)c+='<param name="movie" value="'+a.src+'" />';a.width=a.height=a.id=a.Ka=a.src=null;a.jc=a.version=a.Sb=null;for(var e in a)a[e]&&(c+='<param name="'+e+'" value="'+
a[e]+'" />');e="";if(b){for(var f in b)if(b[f]){var g=b[f];e+=f+"="+(/function|object/.test(typeof g)?N.qa(g):g)+"&"}e=e.slice(0,-1);c+='<param name="flashvars" value=\''+e+"' />"}return c+"</object>"},isSupported:function(a){return C[0]>a[0]||C[0]==a[0]&&C[1]>=a[1]}}),C=d.La=N.Wb();d.Xb=null!=C&&0<C.length&&0<parseFloat(C[0]);d.Xb||(C=d.La=[0,0]);g.h=function(a,b){a||(a="STORAGE");this.ha=a.replace(/[- ]/g,"");g.h.r||g.h.eb();this.W=b||{};this.data={};this.wb=new E;this.Ea=0;this.rc=4E3;this.bc=
!0};g.h.prototype.set=function(a,b){this.oa();this.r[a]=b;this.sa()};g.h.prototype.get=function(a){this.oa();return a?this.r[a]:this.r};g.h.prototype.fa=function(a){this.oa();delete this.r[a];this.sa()};g.h.prototype.fc=function(){this.Ea=0;this.r={};var a=this.W.duration;this.W.duration=-1;this.sa();a?this.W.duration=a:delete this.W.duration};g.h.prototype.oa=function(){this.r={};try{var a=g.h.Y(this.ha);a&&0<a.length&&(this.r=d.parse(a),d.l(this.r)?(this.Ea=this.ha.length+a.length+2,this.bc=!1):
this.r={})}catch(b){this.r={}}};g.h.prototype.sa=function(){var a=d.stringify(this.r);this.ha.length+d.ga(a).length>this.rc&&this.wb.C(this);this.Ea=g.h.write(this.ha,a,this.W)};g.h.Y=function(a){return(a=l.document.cookie.match("(?:^|;)\\s*"+d.Rb(a)+"=([^;]*)"))?d.ta(a[1]):null};g.h.write=function(a,b,c){b=c&&d.l(c.encode)&&!c.encode?b:d.ga(b);a=d.ga(a);for(var e in c)if(c[e]){var f=c[e];b+=";"+("duration"===e?"expires":e);switch(e){case "duration":b+="="+(new Date(d.now()+f*d.Ma)).toGMTString();
default:b+="="+f}}l.document.cookie=a+"="+b;return a.length+b.length+2};g.h.fc=function(a,b){g.h.write(a,"",d.n(b,{duration:-1}))};g.h.eb=function(a){a&&a.apply(g.h)};g.h.isSupported=function(){return!0};q.A={};q.A.set=function(a,b,c,d){c=L(d);c[1][a]=b;c[0].set("cp",c[1])};q.A.get=function(a,b){return L(b)[1][a]};q.A.Za=function(a,b){var c=L(b);delete c[1][a];c[0].set("cp",c[1])};q.A.append=function(a,b,c,d){d=L(d);d[1][a]=d[1][a]?d[1][a]+","+b:b;c&&(b=d[1][a].split(","),c=b.length>c?b.length-c:
0,d[1][a]=b.splice(c,b.length-1-c+1).join());d[0].set("cp",d[1])};q.A.s=function(a){a=a||g.g();var b=a.get("sd");d.l(b)||(b=a.get("cd"));b=m.Ga[b];a={browser:u.f.name+" "+u.f.version,os:u.p.name.match(/ipod|ipad|iphone/i)?"iOS":u.p.name,pv:a.get("pv"),url:x(a,"c"),entry:x(a,"ep"),ref_url:x(a,"ru"),locale:x(a,"l"),site:x(m.site.name),section:x(b.section),referrer:x(a,"r"),terms:x(a,"st"),sessionid:x(a,"rid"),replay_id:x(a,"mid"),flash:d.La.join(".")};u.p.name.match(/android|ipod|ipad|iphone|blackberry|firefox/i)&&
(a.screen=screen.width+"x"+screen.height);v.meta.user_agent&&(a.user_agent=u.pa);if(v.analytics.google_local||v.analytics.google){var c=g.h.Y("__utma"),b=g.h.Y("__utmz");c&&""!=c&&(c=c.split("."),a.first=c[2],a.last=c[3],a.current=c[4],a.visits=c[5]);if(b&&""!=b){var e,c=[];e=["utmgclid","utmcsr","utmccn","utmcmd","utmctr"];for(var f=0;f<e.length;f++)c.push(RegExp(e[f]+"=([^\\|]*)"));if(b.match(c[0]))a.source="Google",a.campaign="Google Adwords",a.medium="cpc";else{if(e=b.match(c[1]))a.source=e[1];
if(e=b.match(c[2]))a.campaign=e[1];if(e=b.match(c[3]))a.medium=e[1]}if(e=b.match(c[4]))a.keyword=e[1]}}b=g.g("cp");c=g.g("meta");a=d.n({},b||{},a||{},c||{});return n.s(a,"cpp")};p=q.A;l.FSR.CPPS=p;p.set=p.set;p.get=p.get;p.erase=p.Za;p.append=p.append;var X={};l.ForeSee=X;X.CPPS=p;p.fsr$set=p.set;p.fsr$get=p.get;p.fsr$erase=p.Za;p.fsr$append=p.append;q.o={};q.o.T=function(){var a,b=v.analytics.google_remote;if(b){var c=m.site.domain;b[c]&&(a=b[c])}return a};q.o.s=function(a){var b={},c=q.o.T();c&&
(b.domain="."+m.site.domain,b.id=c.id,b.name=c.name,a&&(b.event=a));return n.s(b,"ga")};q.o.ab=function(a){var b,c=q.o.T();c&&c.events&&(b=c.events[a]);return b};q.o.fireEvent=function(a){var b=q.o.T();b&&(l._gaq=l._gaq||[],(a=q.o.ab(a))&&l._gaq.push(["_trackEvent","foresee survey",a,b.name]))};q.o.Ub=function(a){var b=a;q.o.T()&&l._gat&&(b=l._gat._getTrackerByName()._getLinkerUrl(a));return b};q.o.ac=function(){var a=q.o.T();if(a){l._gaq=l._gaq||[];l._gaq.push(["_setAccount",a.id]);l._gaq.push(["_setDomainName",
"."+m.site.domain]);l._gaq.push(["_trackPageview"]);a=document.createElement("script");a.type="text/javascript";a.async=!0;a.src=("https:"==document.location.protocol?"https://ssl":"http://www")+".google-analytics.com/ga.js";var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)}};q.P=function(a){a=a&&a.survey||{};this.Cb={name:a.host||"survey.foreseeresults.com"};this.Db={name:a.events_host||"events.foreseeresults.com"};this.Ab={name:".4seeresults.com"};this.Cc={name:"i.4see.mobi"};
this.Hb=a.protocol||d.R()};q.P.prototype.tc=function(){return{host:this.Cb.name,path:"/survey",url:"/display",protocol:this.Hb}};q.P.prototype.Wa=function(){return{host:"controller"+this.Ab.name,path:"/fsrSurvey",url:"/OTCImg",I:3}};q.P.prototype.event=function(){return{host:this.Db.name,path:"/rec",url:"/process"}};d.M(function(){m.siteid=n.Aa("siteid");m.site=m.sites[m.siteid];m.site.name||(m.site.name=n.Aa("name"));m.site.domain||(m.site.domain=n.Aa("domain"));"default"==m.site.domain&&(m.site.domain=
null);for(var a="files js_files image_files html_files css_files swf_files".split(" "),b=0;b<a.length;b++){var c=a[b];m.site[c]||m[c]&&(m.site[c]=m[c])}});d.e=function(a){d.n(this,{options:d.n({},a),mb:!1,v:!1,Q:null,N:null,ka:null,q:null});m.controller=this;this.yc()};d.e.loaded=new E;d.e.nb=new E;d.e.ib=new E;d.e.lb=new E;d.e.prototype.yc=function(){if(d.e.da.va)for(var a=[["loaded",d.e.loaded],["initialized",d.e.Pc],["trackerCanceled",d.e.nb],["qualifierShown",d.e.ib],["surveyShown",d.e.lb]],b=
0;b<a.length;b++){var c=a[b];d.D(d.e.da.va[c[0]])&&c[1].sc(d.e.da.va[c[0]])}};d.e.prototype.load=function(){if("Chrome"!=u.f.name&&!("Firefox"==u.f.name&&4<=u.f.version||"Safari"==u.f.name&&5<=u.f.version)){var a=document.getElementById("hide");a&&(a.style.display="block")}if(this.v)return this;this.v=!0;q.ic(function(a){return function(){a.pc()}}(this),m.embedded)};d.e.prototype.pc=function(){d.e.loaded.C();g.g("t",1);q.o.ac();this.qc();this.Q=this.jb();this.ka=d.now();this.N=setInterval(function(a){return function(){a.Wa()}}(this),
500)};d.e.prototype.wc=function(){this.v&&(g.g("t",0),clearInterval(this.N),this.v=!1,this.mb||(g.g("rc",!0),d.e.nb.C(this.q,g.g()),q.log("201")))};d.e.prototype.Wa=function(){var a=this.jb(),b=g.g("fo")||0,c=g.g("to")||v.tracker.timeout,e=v.tracker.pause||6;if(a==this.Q){try{if(l.opener.document)return}catch(f){}"1"!=this.paused?(d.now()-this.ka)/1E3>=c&&(clearInterval(this.N),this.Ba()):(d.now()-this.ka)/1E3>e&&(clearInterval(this.N),this.Ba())}else if(0!=b)clearInterval(this.N),this.Ba(1!=b);else if(this.Q=
a,this.ka=d.now(),this.paused=0,"paused"==this.Q||"suspended"==this.Q)this.paused=1};d.e.prototype.Ba=function(a){this.mb=!0;this.Nb();this.gc(a||this.q.pop.pu)};d.e.prototype.Nb=function(){var a=g.g(),b=a.get("sd");d.l(b)||(b=a.get("cd"));a=m.Ga[b];a.idx=b;a.survey=d.V(v.survey,a.survey||{});a.qualifier=d.V(v.qualifier,a.qualifier||{});a.pop=d.V(v.pop,a.pop||{});a.tracker=d.V(v.tracker,a.tracker||{});this.q=a};d.e.prototype.gc=function(a){g.g("s",1);"qualifier"!=this.q.pop.what?this.nc(a):this.mc(a)};
d.e.prototype.nc=function(a){d.e.lb.C(this.q,g.g());q.log("400",g.g("c")||"");var b=(new q.P(v)).tc(),c=this.q.survey,e=(l.screen.width-c.width)/2,f=(l.screen.height-c.height)/2,k=d.R(),h=b.host,p=b.path,s=new Date-0+"_"+Math.round(1E13*Math.random()),r=n.hash(s),t=g.g("c")||"",r={sid:q.Vb(this.q,this.q.pop.later),cid:m.id,pattern:t,a:s,b:r,c:d.Ma,version:m.version},t=q.A.s(),s=q.o.s(q.o.ab("survey_shown")),r=n.s(r),b=k+"//"+h+p+b.url+"?"+r+"&"+t;s&&""!=s&&(b=b+"&"+s);b=q.o.Ub(b);this.pop(b,e,f,c.width,
c.height,a)};d.e.prototype.mc=function(a){d.e.ib.C(this.q,g.g());q.log("300",g.g("c")||"");var b=this.q.qualifier;this.page(b);var c=(l.screen.width-b.width)/2,e=(l.screen.height-b.height)/2,f=n.ua(m.site,"html_files","files")+(b.url.pop||b.url),k={siteid:m.siteid,name:m.site.name,domain:m.site.domain};this.q.pop.later&&(k.when=this.q.pop.later);k=n.s(k);this.pop(f+("?"+k),c,e,b.width,b.height,a)};d.e.prototype.pop=function(a,b,c,d,f,k){var h=this.q.tracker;!k&&("Chrome"===u.f.name&&h.alert&&h.alert.enabled)&&
(this.page(h.alert),alert(h.alert.message));setTimeout(function(){l.moveTo(b,c);l.resizeTo(d,f);if(k){l.blur();try{l.opener.focus()}catch(h){}}else l.focus();g.g().fa("t");clearInterval(this.N);t.location.href=a},0)};d.e.prototype.page=function(a){var b=g.g("l");if(b)for(var c=a.locales||[],d=0,f=c.length;d<f;d++)if(c[d].locale==b){c[d].url&&(a.url=c[d].url);c[d].message&&(a.message=c[d].message);c[d].accept&&(a.accept=c[d].accept);c[d].decline&&(a.decline=c[d].decline);c[d].width&&(a.width=c[d].width);
c[d].height&&(a.height=c[d].height);break}};d.e.prototype.jb=function(){return g.h.Y(g.bb("fsr.a"))};d.e.prototype.qc=function(){if(!d.l(m.heartbeat)||m.heartbeat)t.cookie="fsr.a"+(m.site.cookie?"."+m.site.cookie:"")+"="+d.now()+";path=/"+(m.site.domain?";domain="+m.site.domain+";":";")+(m.site.secure?"secure":"")};d.M(function(){(new d.e).load();n.k.ca(l,"unload",function(){m.controller.wc()})});d.e.da={va:{loaded:A(),trackerCanceled:A(),qualifierShown:A(),surveyShown:A()}}})(self,$$FSR);
})({});
}
// -------------------------------- DO NOT MODIFY ANYTHING BETWEEN THE DASHED LINES --------------------------------
