var $$FSR = {
   'timestamp': 'May 8, 2014 @ 4:25 PM',
   'version': '16.1.2.4',
   'build': '7',
   'enabled': true,
   'frames' : false,
   'sessionreplay': true,
   'auto' : true,
   'encode' : true,
   'files': '/frontend/utilities/foresee/',
   // needs to be set when foresee-transport.swf is not located at 'files'
   //'swf_files': '__swf_files_'
   'id': 'kzbIv02ODGyOI0exo0z+uQ==',
   'definition': 'foresee-surveydef.js',
   'swf' : 'foresee-transport.swf',
   'worker' : 'foresee-worker.js',
   'embedded': false,
   'replay_id': 'mystream.com',
   'attach': false,
   'renderer':'W3C',	// or "ASRECORDED"
   'layout':'CENTERFIXED',	// or "LEFTFIXED" or "LEFTSTRETCH" or "CENTERSTRETCH"
   'triggerDelay': undefined,
   'heartbeat' : true,
   'pools' : [
      {
         path: '.',
         sp: 100  // CHANGE ONLY WHEN INCLUDING SESSION REPLAY
      }
   ],
   'sites': [
      {
         path: /\w+-?\w+\.(com|org|edu|gov|net|co\.uk)/
      },
      {
         path: '.',
         domain: 'default'
      }
   ],
   storageOption: 'cookie',
   nameBackup:window.name
};

var FSRCONFIG = {};

// -------------------------------- DO NOT MODIFY ANYTHING BETWEEN THE DASHED LINES --------------------------------
if (typeof(FSR) == "undefined") {
(function(config){(function(P,L){function I(a,b,c){var e=[];if(0<a.length){var f,k,h,g,m=a;a=/\.(?=([^"]*"[^"]*")*[^"]*$)|\[|#|:/g;var l=[];if(a.test(m)){a=m.match(a);for(var n=0;n<a.length;n++){var p=m.indexOf(a[n]);l.push({P:m.substr(0,p),Ia:a[n]});m=m.substr(p)}}l.push({P:m});a=l[0].P.toUpperCase();for(m=l.length-1;1<=m;m--)n=l[m-1].Ia,p=l[m].P,"["==n?(k=p.substr(1,p.length-2).split("="),1<k.length&&(k[1]=k[1].replace(/["']/g,""))):"."==n?h=p.substr(1):"#"==n?f=p.substr(1):":"==n&&(g=parseInt(p.replace(":nth-child(",
"").replace(")","")));0==a.length&&(a="*");if(c)for(m=b.childNodes.length-1;0<=m;m--)c=b.childNodes[m],1!=c.nodeType||"*"!=a&&c.tagName!=a||e.push(c);else e=J(b.getElementsByTagName(a));if(f||k||h||g)for(m=e.length-1;0<=m;m--)g&&d.xa(e[m])!=g-1||h&&-1==e[m].className.indexOf(h)||f&&e[m].id!=f?e.splice(m,1):k&&""!=k[0]&&(b=k[0],c=k[1]||"",l=e[m].getAttribute(b)||"","id"==b?c!=l&&e.splice(m,1):0>l.indexOf(c)&&e.splice(m,1))}return e}function J(a){var b=[],c,e=0;for(c=b.length=a.length;e<c;e++)b[e]=
a[e];return b}function D(a,b){var c,e,d,k,h=q,g,m=b[a];m&&("object"===typeof m&&"function"===typeof m.toJSON)&&(m=m.toJSON(a));"function"===typeof t&&(m=t.call(b,a,m));switch(typeof m){case "string":return E(m);case "number":return isFinite(m)?String(m):"null";case "boolean":case "null":return String(m);case "object":if(!m)return"null";q+=x;g=[];if("[object Array]"===Object.prototype.toString.apply(m)){k=m.length;for(c=0;c<k;c+=1)g[c]=D(c,m)||"null";d=0===g.length?"[]":q?"[\n"+q+g.join(",\n"+q)+"\n"+
h+"]":"["+g.join(",")+"]";q=h;return d}if(t&&"object"===typeof t)for(k=t.length,c=0;c<k;c+=1)"string"===typeof t[c]&&(e=t[c],(d=D(e,m))&&g.push(E(e)+(q?": ":":")+d));else for(e in m)Object.prototype.hasOwnProperty.call(m,e)&&(d=D(e,m))&&g.push(E(e)+(q?": ":":")+d);d=0===g.length?"{}":q?"{\n"+q+g.join(",\n"+q)+"\n"+h+"}":"{"+g.join(",")+"}";q=h;return d}}function E(a){F.lastIndex=0;return F.test(a)?'"'+a.replace(F,function(a){var c=M[a];return"string"===typeof c?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+
'"':'"'+a+'"'}var d={},n=n=window,p=n.document;d.ia=864E5;d.v=!!p.attachEvent;var y=Object.prototype.hasOwnProperty,u=[],z=!1,w,u=[],z=!1;d.c=function(a){return null!==a&&void 0!==a};d.ua=function(a){for(var b=a.length-1;0<=b;b--)for(var c=b-1;0<=c;c--)a[c]==a[b]&&a.splice(b,1);return a};d.xa=function(a){for(var b=a.parentNode.childNodes,c,e=count=0;(c=b.item(e++))&&c!=a;)1==c.nodeType&&count++;return count};d.N=function(a){return"[object Array]"==Object.prototype.toString.call(a)};d.fa=function(a){if(a){if(a.length)for(var b=
a.length-1;0<=b;b--)a[b]=null;for(var c in a)if(b=typeof a[c],"function"==b||"object"==b)a[c]=null}};d.l=function(a){return"function"==typeof a};d.Da=function(a){return"object"==typeof a};d.trim=function(a){return a.toString().replace(/\s+/g," ").replace(/^\s+|\s+$/g,"")};d.$a=function(a){var b=a.getAttribute?a.getAttribute("id"):a.id;b&&!d.gb(b)&&(b=a.attributes.id.value);return b};d.ya=function(a){return a.toString().replace(/([-.*+?^${}()|[\]\/\\])/g,"\\$1")};d.i=function(){var a=arguments,b=a[0]||
{},c=1,e=a.length,f,k,h;"object"===typeof b||d.l(b)||(b={});e===c&&(b=this,--c);for(;c<e;c++)if(null!=(f=a[c]))for(k in f)h=f[k],b!==h&&void 0!==h&&(b[k]=h);return b};d.B=function(){};d.now=function(){return+new Date};d.shift=function(a){return a.splice(0,1)[0]};d.W=function(a,b){for(var c in b)if(b[c]===a)return c;return-1};d.Y=function(){return p.location.protocol};d.eb=function(a,b){return-1!=d.W(a,b)};d.Wa=function(a){return p.getElementById(a)};d.Xa=function(a,b,c){var e=a.split(".");b=b[d.shift(e)];
for(var f=c,k;null!=b&&0<e.length;)b=b[d.shift(e)];if(b){for(e=a.split(".");e.length&&(k=d.shift(e));)f=f[k]?f[k]:f[k]={};e=a.split(".");for(f=c;e.length&&(k=d.shift(e));)0<e.length?f=f[k]:f[k]=b}};d.A=function(){return p.location.href};d.s=function(a){return encodeURIComponent(a)};d.K=function(a){return decodeURIComponent(a)};d.Z=function(){return p.referrer};d.jb={};d.Ea=function(a,b){a=a+"?build="+g.build;b=b||d.B;var c=p.createElement("script");c.type="text/javascript";d.v?c.onreadystatechange=
function(){"loaded"!=this.readyState&&"complete"!=this.readyState||b("ok")}:c.onload=function(){b("ok")};c.onerror=function(){b("error")};c.src=0==d.W("//",a)?d.Y()+a:a;(p.getElementsByTagName("head")[0]||p.documentElement).appendChild(c)};d.q=function(a,b,c){c||(c=n);c=c.document;c=c.readyState;b=b||1;if(d.l(a)&&(a=function(a,b){return function(){setTimeout(function(a){return function(){a.call(d.I);a=null}}(a),b);a=null}}(a,b),c&&("complete"==c||"loaded"==c))){z=!0;for(u.push(a);a=d.shift(u);)a&&
a.call(d.I);return}if(!z&&d.l(a))u.push(a);else if(z&&d.l(a))a.call(d.I);else if(!d.l(a))for(z=!0;0<u.length;)(a=d.shift(u))&&a.call(d.I);a=c=c=c=null};p.addEventListener?w=function(){-1<"complete,loaded".indexOf(p.readyState)&&(p.removeEventListener("readystatechange",w,!1),d.q(null))}:d.v&&(w=function(){-1<"complete,loaded".indexOf(p.readyState)&&(p.detachEvent("onreadystatechange",w),d.q(null))});p.addEventListener?(p.addEventListener("readystatechange",w,!1),p.addEventListener("DOMContentLoaded",
d.q,!1)):d.v&&p.attachEvent("onreadystatechange",w);d.match=function(a){for(var b=[["urls",d.A()],["local",d.A()],["referrers",d.Z()],["referrer",d.Z()],["userAgents",n.navigator.userAgent],["browsers",{name:BROWSER.X.name,version:BROWSER.X.ta}]],c=0;c<b.length;c++)for(var e=b[c],f=a[e[0]]||[],k=0;k<f.length;k++){var g=f[k];if(!d.Da(e[1])){if(d.K(e[1]).match(g))return!0}else if(d.K(e[1].name.toLowerCase()).match(g.name.toLowerCase())&&(!g.version||e[1].version==g.version))return!0}f=a.cookies||[];
for(c=0;c<f.length;c++)if(e=f[c],b=h.a.ea(e.name))if(!e.operator||"eq"==e.operator){if(b.match(e.value||"."))return!0}else if((e.operator||"neq"==e.operator)&&null==b.match(e.value))return!0;c=h.e("fsr.ipo",h.d("fsr.ipo"));if(a=a.variables)for(e=0,f=a.length;e<f;e++)if(b=a[e].name,k=a[e].value,b!=A.ipexclude||1!=c.get("value")){d.N(b)||(b=[b],k=[k]);for(var l,g=!0,m=0,p=b.length,q=k.length;m<p&&m<q;m++){try{l=(new Function("return "+b[m]))(),d.c(l)||(l="")}catch(r){l=""}var s;a:{s=l;var t=k[m];d.N(t)||
(t=[t]);for(var u=0,v=t.length;u<v;u++)if((s+"").match(t[u])){s=!0;break a}s=!1}if(!s){g=!1;break}}if(g)return!0}return!1};d.startTime=d.now();var A={},g=d.i({replay_id:"sitecom",site:{domain:"site.com"},renderer:"W3C",layout:"",swf_files:"/"},L||{});d.Ga=function(){for(var a={},b=arguments,c=0,e=b.length;c<e;c++){var f=b[c];if(d.w(f))for(var k in f){var g=f[k],h=a[k];a[k]=h&&d.w(g)&&d.w(h)?d.Ga(h,g):d.S(g)}}return a};d.S=function(a){var b;if(d.w(a)){b={};for(var c in a)b[c]=d.S(a[c])}else if(d.N(a)){b=
[];c=0;for(var e=a.length;c<e;c++)b[c]=d.S(a[c])}else b=a;return b};d.w=function(a){if(!a||("[object Object]"!==Object.prototype.toString.call(a)||a.nodeType||a.setInterval)||a.constructor&&!y.call(a,"constructor")&&!y.call(a.constructor.prototype,"isPrototypeOf"))return!1;for(var b in a);return void 0===b||y.call(a,b)||!y.call(a,b)&&y.call(Object.prototype,b)};d.L=function(){u=g=null;d=n=n.FSR=null};d.bb=function(a){var b=d.now(),c;do c=d.now();while(c-b<a)};if(d.c(n.FSRCONFIG)){var r=n.FSRCONFIG;
r.surveydefs&&(d.surveydefs=r.surveydefs,r.surveydefs=null);r.properties&&(d.properties=r.properties,r.properties=null)}n.FSR=d;n.FSR.opts=g;n.FSR.prop=A;d.g={};d.g.qa={};var l=d.g.qa;l.Za=function(){for(var a=BROWSER.Ua.replace(/[\s\\\/\.\(\);:]/gim,""),b="",c=d.now()+"",e=0;e<a.length-1;e+=a.length/7)b+=Number(a.charCodeAt(Math.round(e))%16).toString(16);7<b.length&&(b=b.substr(b.length-7));return b+"-"+a.length+c.substr(c.length-6)+"-xxxx-xxxx-xxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|
0;return("x"==a?b:b&3|8).toString(16)})};l.mb=function(a,b){return a+Math.random()*(b-a)};l.pb=function(a,b){var c=n.document.createElement("a");c.href=n.location.href;var e=c.hostname,d=c.protocol;c.href=a;var k=c.hostname||e,g=0==c.protocol.indexOf("http")?c.protocol:d;c.href=b;d=0==c.protocol.indexOf("http")?c.protocol:d;return k.toLowerCase()==(c.hostname||e).toLowerCase()&&g.toLowerCase()==d.toLowerCase()};l.La=function(a){var b="";if(a)for(var c in a)b+=(0!=b.length?"&":"")+c+"="+d.s(a[c]);
return b};l.hash=function(a){a=a.split("_");return 3*a[0]+1357+""+(9*a[1]+58)};l.cb=function(a){var b=0,c="";if(0==a.length)return b;for(s=0;s<a.length;s++)c=a.charCodeAt(s),b=(b<<5)-b+c,b&=b;return b};l.lb=function(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");a=RegExp("[\\?&+]"+a+"=([^&#]*)").exec(d.A());return null==a?!1:a[1]};l.wa=function(a){return a.js_files||a.files};l.ib=function(a){a=a.replace(/[^0-9]/g,"");return 10==a.length||"1"==a[0]&&11==a.length};l.hb=function(a){return null!=
a.match(/^([a-zA-Z0-9_\.\-\+])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,6})+$/)};d.g.ka={};var v=d.g.ka;d.g.ha={};r=d.g.ha;r.Ta=function(a,b){var c,e,f;d.c(a.length)||(a=[a]);c=0;for(e=a.length;c<e;c++){f=a[c];var k=f.className||"";RegExp("\\b"+b+"\\b").test(k)||(f.className=(""==k?"":k+" ")+b)}};r.nb=function(a,b){var c,e,f;d.c(a.length)||(a=[a]);c=0;for(e=a.length;c<e;c++)f=a[c],f.className&&(f.className=f.className.replace(RegExp("(\\s|^)"+b+"(\\s|$)")," ").replace(/^\s+|\s+$/g,""))};r.Ya=function(a,
b){if(a){d.c(a.length)||(a=[a]);for(var c=0;c<a.length;c++)for(var e in b)e&&(-1=="zIndex".indexOf(e)&&("number"==typeof b[e]&&"opacity"!=e)&&(b[e]+="px"),a[c].style[e]=b[e])}return a};r.Va=function(a,b){if(a){d.c(a.length)||(a=[a]);for(var c=0;c<a.length;c++)for(var e in b)a[c].setAttribute(e,b[e])}return a};r.outerHTML=function(a){if(d.c(a.outerHTML))return a.outerHTML;var b={TEXTAREA:!0},c={HR:!0,BR:!0,IMG:!0,INPUT:!0},e=[],f="",k=a.nodeName;switch(a.nodeType){case 1:f=f+"<"+k.toLowerCase();if(b[k])switch(k){case "TEXTAREA":for(b=
0;b<a.attributes.length;b++)if("value"!=a.attributes[b].nodeName.toLowerCase())f+=" "+a.attributes[b].nodeName.toUpperCase()+'="'+a.attributes[b].nodeValue+'"';else var g=a.attributes[b].nodeValue;f+=">";f+=g;f+="</"+k+">"}else{for(b=a.attributes.length-1;0<=b;b--)g=a.attributes[b].nodeName.toLowerCase(),-1<"style,class,id".indexOf(g.toLowerCase())&&(f+=" "+g+'="'+a.attributes[b].nodeValue+'"');f+=">";c[k]||(f+=a.innerHTML,f+="</"+k.toLowerCase()+">")}break;case 3:f+=a.nodeValue;break;case 8:f+="\x3c!--"+
a.nodeValue+"--\x3e"}e.push(f);return e.join("")};for(var G={},B=["onload","onerror","onabort"],s=0;s<B.length;s++)G[B[s]]=function(){this.Ha(0==arguments.callee.Ba?1:0);this.C=!1},G[B[s]].Ba=s;v.k=function(a,b){this.options=d.i({},a);this.C=!1;this.event=b;this.T=0;return this};v.k.prototype.Ha=function(a){if(this.C)switch(this.C=!1,this.status=a,a){case 1:(this.options.onSuccess||d.B)(void 0);break;case 0:this.event?this.Ma():(this.options.onFailure||d.B)(void 0);break;case -1:(this.options.onError||
d.B)(void 0)}};v.k.prototype.Ma=function(){if(3>this.T)this.V();else this.onFailure()};v.k.prototype.sa=function(a){var b;this.C=!0;a=l.La(d.i(a,{uid:d.now()}));a=d.Y()+"//"+this.options.host+this.options.path+this.options.url+"?"+a;b=d.i({},G,b);for(var c=new Image,e=0;e<B.length;e++){var f=B[e];c[f]=function(){var a=arguments.callee;a.o.onload=a.o.onerror=a.o.onabort=null;a.Aa.call(a.self,a.o);a.o=null};c[f].Aa=b[f];c[f].o=c;c[f].self=this}c.src=a};v.k.prototype.send=function(a){this.Na=a;this.V()};
v.k.prototype.V=function(){var a;this.T++;a=d.i({event:this.event,ver:this.T},this.Na,a);this.sa(a)};d.g.na={};var h=d.g.na;h.t=function(a){return a+(g.site.cookie?"."+g.site.cookie:"")};h.M=function(a){var b=h.t("fsr.s"),b=h.e(b,h.d(b));return a?d.c(void 0)?b.set(a,void 0):b.get(a):b};h.d=function(a,b){var c;c="window"==g.storageOption&&h.ra.isSupported()?function(){var a=arguments.callee;return new h.ra(a.da,a.ba||{})}:function(){var a=arguments.callee;return new h.a(a.da,d.i({path:"/",domain:a.O.site.domain,
secure:a.O.site.secure,encode:a.O.encode},a.ba||{}))};c.da=a;c.O=g;c.ba=b;return c};var K={};h.e=function(a,b){var c=K[a];return null!=c?c:c=K[a]=new b};l.b={};l.b.m={};l.b.D=function(a,b,c,e){var f=l.b.m;if(a){f[b]||(f[b]=[]);f[b].push({aa:a,H:c});if("unload"==b){if(d.c(d.r)){d.r.push(c);return}d.r=[]}"propertychange"!=b&&a.addEventListener?a.addEventListener(b,c,!e):a.attachEvent&&a.attachEvent("on"+b,c)}};l.b.Oa=function(a,b,c,d,f){var g=l.b;if(f){if(a.getAttribute("_fsr"+b))return!1;a.setAttribute("_fsr"+
b,"true")}else if(f=g.m[b])for(g=f.length-1;0<=g;g--)if(f[g].aa==a&&(d||f[g].H==c))return!1;l.b.D(a,b,c)};l.b.Pa=function(a,b,c){l.b.D(a,b,c,!0)};l.b.pa=function(a,b,c){try{"propertychange"!=b&&a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+b,c)}catch(d){}};var N=l.b.D;l.b.ja=function(){for(var a=d.r.length-1;0<=a;a--)try{d.r[a].call()}catch(b){}d.fa(d.r);l.b.ma();d.L()};N(n,"unload",l.b.ja);l.b.ma=function(){if(d){var a=l.b,b;for(b in a.m){for(var c=a.m[b],
e={};e=c.pop();)a.pa(e.aa,b,e.H),d.fa(e);delete a.m[b]}}};l.b.U=function(){this.R=[];this.va=!1};l.b.U.prototype.za=function(){this.va=!0;for(var a=0;a<this.R.length;a++){var b=this.R[a];b.H.apply(this,arguments);b.kb&&(this.R.splice(a,1),a--)}};var O=l.b.U;d.stringify=function(a,b,c){var e;n.Prototype&&(e=Array.prototype.toJSON,delete Array.prototype.toJSON);if(n.JSON&&"function"===typeof n.JSON.stringify)a=n.JSON.stringify(a,b,c);else{var f;x=q="";if("number"===typeof c)for(f=0;f<c;f+=1)x+=" ";
else"string"===typeof c&&(x=c);if((t=b)&&"function"!==typeof b&&("object"!==typeof b||"number"!==typeof b.length))throw Error("_4c.stringify");a=D("",{"":a})}d.c(e)&&(Array.prototype.toJSON=e);return a};d.parse=function(a){if(n.JSON&&d.l(n.JSON.parse))return n.JSON.parse(a);a=String(a);H.lastIndex=0;H.test(a)&&(a=a.replace(H,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return(new Function("return "+a))();throw new SyntaxError("_4c.parse");};var H=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,F=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,q,x,M={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},t;r.la={Sa:{}};try{Array.prototype.slice.call(document.getElementsByTagName("html")),
makeArray=function(a){return Array.prototype.slice.call(a)}}catch(Q){}r.la.ob=function(a,b,c){b=b||p;c=!d.c(d.F)||!d.F.Qa.qb||c;if(b.querySelectorAll&&!(d.v&&8>=BROWSER.X.ta&&-1<a.indexOf("nth")))return J(b.querySelectorAll(a));if(!c&&n.$&&!n.Prototype)return n.$(a,b);a=a.split(",");c=[];for(var e=a.length-1;0<=e;e--){var f=a[e].replace(/^\s\s*/,"").replace(/\s\s*$/,"").replace(/\*=/g,"=").replace(/\>/g," > ").replace(/\s+/g," ");if(-1<f.indexOf(" ")){for(var f=f.split(" "),g=[b],h=!1,l=0;l<f.length;l++)if(">"==
f[l])h=!0;else{for(var m=[],q=g.length-1;0<=q;q--)m=m.concat(I(f[l],g[q],h));g=m;h=!1}c=c.concat(d.ua(g))}else c=c.concat(I(f,b))}return c};h.a=function(a,b){a||(a="STORAGE");this.u=a.replace(/[- ]/g,"");this.p=b||{};this.data={};this.oa=new O;this.Q=0;this.Ka=4E3;this.Ca=!0};h.a.prototype.set=function(a,b){this.G();this.h[a]=b;this.J()};h.a.prototype.get=function(a){this.G();return a?this.h[a]:this.h};h.a.prototype.L=function(a){this.G();delete this.h[a];this.J()};h.a.prototype.j=function(){this.Q=
0;this.h={};var a=this.p.duration;this.p.duration=-1;this.J();a?this.p.duration=a:delete this.p.duration};h.a.prototype.G=function(){this.h={};try{var a=h.a.ea(this.u);a&&0<a.length&&(this.h=d.parse(a),d.c(this.h)?(this.Q=this.u.length+a.length+2,this.Ca=!1):this.h={})}catch(b){this.h={}}};h.a.prototype.J=function(){var a=d.stringify(this.h);this.u.length+d.s(a).length>this.Ka&&this.oa.za(this);this.Q=h.a.write(this.u,a,this.p)};h.a.ea=function(a){return(a=n.document.cookie.match("(?:^|;)\\s*"+d.ya(a)+
"=([^;]*)"))?d.K(a[1]):null};h.a.write=function(a,b,c){b=c&&d.c(c.encode)&&!c.encode?b:d.s(b);a=d.s(a);for(var e in c)if(c[e]){var f=c[e];b+=";"+("duration"===e?"expires":e);switch(e){case "duration":b+="="+(new Date(d.now()+f*d.ia)).toGMTString();default:b+="="+f}}n.document.cookie=a+"="+b;return a.length+b.length+2};h.a.j=function(a,b){h.a.write(a,"",d.i(b,{duration:-1}))};h.a.fb=function(){};h.a.isSupported=function(){return!0};d.g.F={};var C=d.g.F;C.ab=function(a,b){for(var c=a.name,d=[a.site,
a.section,b,h.M("q"),h.M("l")],f=0;f<d.length;f++)c+=d[f]?"-"+d[f]:"";return c};C.Fa=function(a,b){function c(b){"ok"===b&&d.surveydefs&&(d.i(A,d.properties),g.ga=g.surveydefs=d.surveydefs,a())}var e=g.definition||"foresee-surveydef.js";b?setTimeout(function(){c("ok")},100):d.Ea(l.wa(g.site)+e,c)};C.log=function(a,b){if(A.events.enabled){var c=h.M(),e=c.get("sd");d.c(e)||(e=c.get("cd"));d.c(e)||(e=0);var e=g.ga[e],f=new Date;(new v.k((new C.Ra(A)).event(),"logit")).send({cid:g.id,rid:c.get("rid")||
"",cat:e.name,sec:e.section||"",type:c.get("q")||"",site:g.site.name||"",lang:c.get("l")||(d.$S?d.$S.locale:""),msg:a,param:b,tms:f.getTime(),tmz:6E4*f.getTimezoneOffset()})}};d.q(function(){for(var a=g.sites,b=0,c=a.length;b<c;b++){var e;"[object Array]"!==typeof a[b].path&&(a[b].path=[a[b].path]);for(var f=0,h=a[b].path.length;f<h;f++)if(e=d.A().match(a[b].path[f])){g.siteid=b;g.site=g.sites[b];g.site.domain?"default"==g.site.domain&&(g.site.domain=null):g.site.domain=e[0];g.site.secure||(g.site.secure=
null);g.site.name||(g.site.name=e[0]);f="files js_files image_files html_files css_files swf_files".split(" ");for(b=0;b<f.length;b++)g.site[f[b]]||g[f[b]]&&(g.site[f[b]]=g[f[b]]);break}if(e)break}});d.f=function(a){d.i(this,{options:d.i({},a)});g.controller=this};d.f.prototype.load=function(){var a=this;C.Fa(function(){a.Ja()},g.embedded)};d.f.n=function(a){for(var b=document.getElementsByTagName("input"),c=[],d=0;d<b.length;d++)b[d].type==a.type&&(a.name?b[d].name==a.name&&c.push(b[d]):c.push(b[d]));
return c};d.f.prototype.Ja=function(){for(var a=h.e("fsr.sp",h.d("fsr.sp")),b=[],c=g.ga,e=0;e<c.length;e++)if(!c[e].site||c[e].site==g.site.name){var f=c[e].criteria;if(d.c(f.sp)){var k=void 0;b.push(this.ca(c[e].name,c[e].section||k,void 0,a,f.sp,f.lf))}for(var f=f.locales||[],l=0,n=f.length;l<n;l++)k=void 0,b.push(this.ca(c[e].name,c[e].section||k,f[l].locale,a,f[l].sp,f[l].lf))}e='<table><tr><td class="names">&nbsp;</td><td colspan="2">Sampling Percentage</td><td>&nbsp;</td><td>Loyalty Factor</td></tr>';
a=0;for(c=b.length;a<c;a++)k=b[a],f=k.input,e+="<tr>",e+='<td class="names">'+k.names+"</td>",e+='<td><input type="text" name="'+f.name+'" value="'+f.value+'" size="'+f.size+'" maxlength="'+f.maxlength+'"></td>',e+="<td>"+k.percentage+"</td>",e+="<td>&nbsp;</td>",e+="<td>"+k.loyaltyFactor+"</td>",e+="</tr>";document.getElementById("controls").innerHTML=e+"</table>";if(1==h.e("fsr.ipo",h.d("fsr.ipo")).get("value"))for(b=d.f.n({type:"checkbox",name:"ipo"}),e=0;e<b.length;e++)b.checked=!0;if(1==h.e("fsr.pool",
h.d("fsr.pool")).get("value"))for(b=d.f.n({type:"checkbox",name:"pool"}),e=0;e<b.length;e++)b.checked=!0};d.f.prototype.ca=function(a,b,c,d,f,g){var h=a;b&&(h+="-"+b,a+="-"+b);c&&(h+=" ("+c+")",a+="-"+c);return{names:h+":",input:{name:a,value:d.get(a)||"",size:3,maxlength:3},percentage:"("+f+")",loyaltyFactor:g}};d.f.prototype.set=function(){for(var a=d.f,b=h.e("fsr.sp",h.d("fsr.sp",{duration:1})),c=a.n({type:"text"}),e=0;e<c.length;e++){var f=c[e];""!=f.value?b.set(f.name,f.value):b.L(f.name)}b=
a.n({type:"checkbox",name:"ipo"})[0];a=a.n({type:"checkbox",name:"pool"})[0];b.checked?h.e("fsr.ipo",h.d("fsr.ipo")).set("value",b.checked?1:0):h.e("fsr.ipo",h.d("fsr.ipo")).j();a.checked?h.e("fsr.pool",h.d("fsr.pool")).set("value",a.checked?1:0):h.e("fsr.pool",h.d("fsr.pool")).j()};d.f.prototype.clear=function(){var a=h,b=a.e;b("fsr.sp",h.d("fsr.sp")).j();b("fsr.ipo",a.d("fsr.ipo")).j();b("fsr.pool",a.d("fsr.pool")).j();a.a.j(a.t("fsr.r"),{path:"/",domain:g.site.domain,secure:g.site.secure});a.a.j(a.t("fsr.s"),
{path:"/",domain:g.site.domain,secure:g.site.secure});a.a.j(a.t("fsr.p"),{path:"/",domain:g.site.domain,secure:g.site.secure});a=document.getElementsByTagName("input");for(b=0;b<a.length;b++){var c=a[b];"text"==c.type?c.value="":"checkbox"==c.type&&(c.checked=!1)}};d.q(function(){var a=new d.f;g.controller.set=a.set;g.controller.clear=a.clear;a.load()})})(self,$$FSR);
})({});
}
// -------------------------------- DO NOT MODIFY ANYTHING BETWEEN THE DASHED LINES --------------------------------
