# If you have OpenSSL installed, we recommend updating
# the following line to use 'https'
source 'http://rubygems.org'

gem 'sass', '>= 3.3.4'
gem 'compass', '~> 1.0.0.alpha.19'
gem 'compass-h5bp', '>= 0.1.2'
gem 'oily_png', '~> 1.1.1'