# If you have OpenSSL installed, we recommend updating
# the following line to use 'https'
source 'http://rubygems.org'

gem 'sass', '>= 3.4.9'
gem 'compass', '>= 1.0.1'
gem 'compass-h5bp', '>= 0.1.2'
gem 'oily_png', '~> 1.1.1'
gem 'wdm', '>= 0.1.0', :platforms => [:mswin, :mingw, :x64_mingw]