//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreamEnergy.Sample.Temperature {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.w3schools.com/webservices/", ConfigurationName="Sample.Temperature.TempConvertSoap")]
    public interface TempConvertSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.w3schools.com/webservices/FahrenheitToCelsius", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StreamEnergy.Sample.Temperature.FahrenheitToCelsiusResponse FahrenheitToCelsius(StreamEnergy.Sample.Temperature.FahrenheitToCelsiusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.w3schools.com/webservices/FahrenheitToCelsius", ReplyAction="*")]
        System.Threading.Tasks.Task<StreamEnergy.Sample.Temperature.FahrenheitToCelsiusResponse> FahrenheitToCelsiusAsync(StreamEnergy.Sample.Temperature.FahrenheitToCelsiusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.w3schools.com/webservices/CelsiusToFahrenheit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StreamEnergy.Sample.Temperature.CelsiusToFahrenheitResponse CelsiusToFahrenheit(StreamEnergy.Sample.Temperature.CelsiusToFahrenheitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.w3schools.com/webservices/CelsiusToFahrenheit", ReplyAction="*")]
        System.Threading.Tasks.Task<StreamEnergy.Sample.Temperature.CelsiusToFahrenheitResponse> CelsiusToFahrenheitAsync(StreamEnergy.Sample.Temperature.CelsiusToFahrenheitRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FahrenheitToCelsius", WrapperNamespace="http://www.w3schools.com/webservices/", IsWrapped=true)]
    public partial class FahrenheitToCelsiusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.w3schools.com/webservices/", Order=0)]
        public string Fahrenheit;
        
        public FahrenheitToCelsiusRequest() {
        }
        
        public FahrenheitToCelsiusRequest(string Fahrenheit) {
            this.Fahrenheit = Fahrenheit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FahrenheitToCelsiusResponse", WrapperNamespace="http://www.w3schools.com/webservices/", IsWrapped=true)]
    public partial class FahrenheitToCelsiusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.w3schools.com/webservices/", Order=0)]
        public string FahrenheitToCelsiusResult;
        
        public FahrenheitToCelsiusResponse() {
        }
        
        public FahrenheitToCelsiusResponse(string FahrenheitToCelsiusResult) {
            this.FahrenheitToCelsiusResult = FahrenheitToCelsiusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CelsiusToFahrenheit", WrapperNamespace="http://www.w3schools.com/webservices/", IsWrapped=true)]
    public partial class CelsiusToFahrenheitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.w3schools.com/webservices/", Order=0)]
        public string Celsius;
        
        public CelsiusToFahrenheitRequest() {
        }
        
        public CelsiusToFahrenheitRequest(string Celsius) {
            this.Celsius = Celsius;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CelsiusToFahrenheitResponse", WrapperNamespace="http://www.w3schools.com/webservices/", IsWrapped=true)]
    public partial class CelsiusToFahrenheitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.w3schools.com/webservices/", Order=0)]
        public string CelsiusToFahrenheitResult;
        
        public CelsiusToFahrenheitResponse() {
        }
        
        public CelsiusToFahrenheitResponse(string CelsiusToFahrenheitResult) {
            this.CelsiusToFahrenheitResult = CelsiusToFahrenheitResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TempConvertSoapChannel : StreamEnergy.Sample.Temperature.TempConvertSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TempConvertSoapClient : System.ServiceModel.ClientBase<StreamEnergy.Sample.Temperature.TempConvertSoap>, StreamEnergy.Sample.Temperature.TempConvertSoap {
        
        public TempConvertSoapClient() {
        }
        
        public TempConvertSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TempConvertSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TempConvertSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TempConvertSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public StreamEnergy.Sample.Temperature.FahrenheitToCelsiusResponse FahrenheitToCelsius(StreamEnergy.Sample.Temperature.FahrenheitToCelsiusRequest request) {
            return base.Channel.FahrenheitToCelsius(request);
        }
        
        public System.Threading.Tasks.Task<StreamEnergy.Sample.Temperature.FahrenheitToCelsiusResponse> FahrenheitToCelsiusAsync(StreamEnergy.Sample.Temperature.FahrenheitToCelsiusRequest request) {
            return base.Channel.FahrenheitToCelsiusAsync(request);
        }
        
        public StreamEnergy.Sample.Temperature.CelsiusToFahrenheitResponse CelsiusToFahrenheit(StreamEnergy.Sample.Temperature.CelsiusToFahrenheitRequest request) {
            return base.Channel.CelsiusToFahrenheit(request);
        }
        
        public System.Threading.Tasks.Task<StreamEnergy.Sample.Temperature.CelsiusToFahrenheitResponse> CelsiusToFahrenheitAsync(StreamEnergy.Sample.Temperature.CelsiusToFahrenheitRequest request) {
            return base.Channel.CelsiusToFahrenheitAsync(request);
        }
    }
}
