//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.layouts.Pages.Marketing.FAQ {
    
    
    public partial class FAQ_Landing {
        
        /// <summary>
        /// faqTexas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Website.layouts.Pages.Marketing.FAQ.FAQ_Listing faqTexas;
        
        /// <summary>
        /// faqGeorgia control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Website.layouts.Pages.Marketing.FAQ.FAQ_Listing faqGeorgia;
        
        /// <summary>
        /// faqPennsylvania control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Website.layouts.Pages.Marketing.FAQ.FAQ_Listing faqPennsylvania;
        
        /// <summary>
        /// faqMaryland control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Website.layouts.Pages.Marketing.FAQ.FAQ_Listing faqMaryland;
        
        /// <summary>
        /// faqNewJersey control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Website.layouts.Pages.Marketing.FAQ.FAQ_Listing faqNewJersey;
        
        /// <summary>
        /// faqNewYork control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Website.layouts.Pages.Marketing.FAQ.FAQ_Listing faqNewYork;
        
        /// <summary>
        /// faqWashingtonDC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Website.layouts.Pages.Marketing.FAQ.FAQ_Listing faqWashingtonDC;
    }
}
