//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreamEnergy.StreamEnergyBilling.IstaTokenization {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetUrlRequest", Namespace="http://schemas.datacontract.org/2004/07/CIS.Clients.Stream.SelfService.Services.C" +
        "ontracts.Data")]
    [System.SerializableAttribute()]
    public partial class GetUrlRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        private string AuthIdField;
        
        private string AuthPwdField;
        
        private string CustomerTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesignatedCustomerField;
        
        private string LanguageField;
        
        private string SourceField;
        
        private string StateAbbrevField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountName {
            get {
                return this.AccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNameField, value) != true)) {
                    this.AccountNameField = value;
                    this.RaisePropertyChanged("AccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string AuthId {
            get {
                return this.AuthIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthIdField, value) != true)) {
                    this.AuthIdField = value;
                    this.RaisePropertyChanged("AuthId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string AuthPwd {
            get {
                return this.AuthPwdField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthPwdField, value) != true)) {
                    this.AuthPwdField = value;
                    this.RaisePropertyChanged("AuthPwd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CustomerType {
            get {
                return this.CustomerTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerTypeField, value) != true)) {
                    this.CustomerTypeField = value;
                    this.RaisePropertyChanged("CustomerType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DesignatedCustomer {
            get {
                return this.DesignatedCustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.DesignatedCustomerField, value) != true)) {
                    this.DesignatedCustomerField = value;
                    this.RaisePropertyChanged("DesignatedCustomer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string StateAbbrev {
            get {
                return this.StateAbbrevField;
            }
            set {
                if ((object.ReferenceEquals(this.StateAbbrevField, value) != true)) {
                    this.StateAbbrevField = value;
                    this.RaisePropertyChanged("StateAbbrev");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StreamEnergyBilling.IstaTokenization.IDpiTokenService")]
    public interface IDpiTokenService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDpiTokenService/GetDpiTokenUrl", ReplyAction="http://tempuri.org/IDpiTokenService/GetDpiTokenUrlResponse")]
        string GetDpiTokenUrl(StreamEnergy.StreamEnergyBilling.IstaTokenization.GetUrlRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDpiTokenService/GetDpiTokenUrl", ReplyAction="http://tempuri.org/IDpiTokenService/GetDpiTokenUrlResponse")]
        System.Threading.Tasks.Task<string> GetDpiTokenUrlAsync(StreamEnergy.StreamEnergyBilling.IstaTokenization.GetUrlRequest req);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDpiTokenServiceChannel : StreamEnergy.StreamEnergyBilling.IstaTokenization.IDpiTokenService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DpiTokenServiceClient : System.ServiceModel.ClientBase<StreamEnergy.StreamEnergyBilling.IstaTokenization.IDpiTokenService>, StreamEnergy.StreamEnergyBilling.IstaTokenization.IDpiTokenService {
        
        public DpiTokenServiceClient() {
        }
        
        public DpiTokenServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DpiTokenServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DpiTokenServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DpiTokenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDpiTokenUrl(StreamEnergy.StreamEnergyBilling.IstaTokenization.GetUrlRequest req) {
            return base.Channel.GetDpiTokenUrl(req);
        }
        
        public System.Threading.Tasks.Task<string> GetDpiTokenUrlAsync(StreamEnergy.StreamEnergyBilling.IstaTokenization.GetUrlRequest req) {
            return base.Channel.GetDpiTokenUrlAsync(req);
        }
    }
}
